#include "text/message_data.h"
#include "config.h"

#if ENABLE_MM_TITLE_CARDS

DEFINE_MESSAGE(0x8000, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Deku Tree")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8001, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Dodongos Cavern")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8002, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Jabu Jabu")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8003, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Forest Temple")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8004, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Fire Temple")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8005, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Water Temple")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8006, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Spirit Temple")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8007, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Shadow Temple")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8008, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Bottom Of The Well")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8009, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Ice Cavern")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x800A, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Ganons Tower")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x800B, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Gerudo Training Ground")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x800C, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Thieves Hideout")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x800D, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Inside Ganons Castle")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x800E, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Ganons Tower Collapse Interior")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x800F, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Inside Ganons Castle Collapse")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8010, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Treasure Box Shop")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8011, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Deku Tree Boss")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8012, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Dodongos Cavern Boss")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8013, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Jabu Jabu Boss")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8014, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Forest Temple Boss")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8015, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Fire Temple Boss")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8016, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Water Temple Boss")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8017, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Spirit Temple Boss")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8018, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Shadow Temple Boss")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8019, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Ganondorf Boss")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x801A, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Ganons Tower Collapse Exterior")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x801B, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Market Entrance Day")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x801C, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Market Entrance Night")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x801D, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Market Entrance Ruins")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x801E, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Back Alley Day")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x801F, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Back Alley Night")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8020, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Market Day")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8021, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Market Night")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8022, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Market Ruins")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8023, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Temple Of Time Exterior Day")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8024, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Temple Of Time Exterior Night")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8025, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Temple Of Time Exterior Ruins")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8026, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Know It All Bros House")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8027, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Twins House")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8028, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Midos House")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8029, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Sarias House")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x802A, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Kakariko Center Guest House")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x802B, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Back Alley House")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x802C, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Bazaar")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x802D, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Kokiri Shop")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x802E, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Goron Shop")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x802F, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Zora Shop")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8030, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Potion Shop Kakariko")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8031, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Potion Shop Market")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8032, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Bombchu Shop")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8033, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Happy Mask Shop")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8034, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Links House")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8035, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Dog Lady House")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8036, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Stable")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8037, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Impas House")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8038, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Lakeside Laboratory")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8039, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Carpenters Tent")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x803A, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Gravekeepers Hut")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x803B, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Great Fairys Fountain Magic")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x803C, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Fairys Fountain")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x803D, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Great Fairys Fountain Spells")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x803E, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Grottos")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x803F, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Redead Grave")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8040, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Grave With Fairys Fountain")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8041, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Royal Familys Tomb")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8042, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Shooting Gallery")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8043, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Temple Of Time")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8044, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Chamber Of The Sages")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8045, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Castle Courtyard Guards Day")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8046, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Castle Courtyard Guards Night")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8047, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Cutmap")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8048, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Windmill And Dampes Grave")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8049, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Fishing Pond")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x804A, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Castle Courtyard Zelda")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x804B, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Bombchu Bowling Alley")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x804C, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Lon Lon Buildings")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x804D, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Market Guard House")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x804E, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Potion Shop Granny")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x804F, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Ganon Boss")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8050, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("House Of Skulltula")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8051, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Hyrule Field")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8052, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Kakariko Village")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8053, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Graveyard")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8054, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Zoras River")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8055, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Kokiri Forest")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8056, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Sacred Forest Meadow")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8057, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Lake Hylia")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8058, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Zoras Domain")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8059, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Zoras Fountain")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x805A, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Gerudo Valley")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x805B, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Lost Woods")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x805C, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Desert Colossus")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x805D, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Gerudos Fortress")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x805E, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Haunted Wasteland")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x805F, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Hyrule Castle")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8060, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Death Mountain Trail")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8061, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Death Mountain Crater")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8062, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Goron City")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8063, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Lon Lon Ranch")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8064, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Outside Ganons Castle")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8065, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Test01")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8066, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Besitu")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8067, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Depth Test")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8068, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Syotes")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x8069, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Syotes2")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x806A, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Sutaru")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x806B, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Hairal Niwa2")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x806C, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Sasatest")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x806D, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Testroom")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

DEFINE_MESSAGE(0x806E, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG("Example")
,
MSG(/* MISSING */)
,
MSG(/* MISSING */)
)

#endif

/*
 * The following two messages should be kept last and in this order.
 * Message 0xFFFD must be last to not break the message debugger (see R_MESSAGE_DEBUGGER_TEXTID).
 * Message 0xFFFC must be immediately before message 0xFFFD to not break Font_LoadOrderedFont.
 */
DEFINE_MESSAGE_FFFC(0xFFFC, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(
"０１２３４５６７８９あいうえおかきくけこ\n"
"さしすせそたちつてとなにぬねのはひふへほ\n"
"まみむめもやゆよらりるれろわをんぁぃぅぇ\n"
"ぉっゃゅょがぎぐげござじずぜぞだぢづでど\n"
"ばびぶべぼぱぴぷぺぽアイウエオカキクケコ\n"
"サシスセソタチツテトナニヌネノハヒフヘホ\n"
"マミムメモヤユヨラリルレロワヲンァィゥェ\n"
"ォッャュョガギグゲゴザジズゼゾダヂヅデド\n"
"バビブベボパピプペポヴＡＢＣＤＥＦＧＨＩ\n"
"ＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺａｂｃ\n"
"ｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗ\n"
"ｘｙｚ　┯？！：−（）゛゜，．／"
)
,
MSG(
"0123456789\n"
"ABCDEFGHIJKLMN\n"
"OPQRSTUVWXYZ\n"
"abcdefghijklmn\n"
"opqrstuvwxyz\n"
" -.\n"
)
,
MSG(/* UNUSED */)
,
MSG(/* UNUSED */)
)
DEFINE_MESSAGE(0xFFFD, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE, MSG(), MSG(), MSG(), MSG())
