#ifndef OCCLUSIONPLANE_H
#define OCCLUSIONPLANE_H

typedef enum F3DEX3OccMode {
    F3DEX3_OCC_MODE_AUTO,
    F3DEX3_OCC_MODE_ALWAYS,
    F3DEX3_OCC_MODE_NEVER,
    F3DEX3_OCC_MODE_COUNT
} F3DEX3OccMode;

#endif
