#ifndef GAMEPLAY_KEEP_H
#define GAMEPLAY_KEEP_H

#include "animation.h"
#include "bgcheck.h"
#include "tex_len.h"
#include "ultra64.h"
#include "z_math.h"

#define gHilite1Tex_WIDTH 16
#define gHilite1Tex_HEIGHT 16
extern u64 gHilite1Tex[TEX_LEN(u64, gHilite1Tex_WIDTH, gHilite1Tex_HEIGHT, 16)];
#define gHilite2Tex_WIDTH 16
#define gHilite2Tex_HEIGHT 16
extern u64 gHilite2Tex[TEX_LEN(u64, gHilite2Tex_WIDTH, gHilite2Tex_HEIGHT, 16)];
#define gHylianShieldDesignTex_WIDTH 32
#define gHylianShieldDesignTex_HEIGHT 64
extern u64 gHylianShieldDesignTex[TEX_LEN(u64, gHylianShieldDesignTex_WIDTH, gHylianShieldDesignTex_HEIGHT, 16)];
#define gOcarinaofTimeDesignTex_WIDTH 32
#define gOcarinaofTimeDesignTex_HEIGHT 16
extern u64 gOcarinaofTimeDesignTex[TEX_LEN(u64, gOcarinaofTimeDesignTex_WIDTH, gOcarinaofTimeDesignTex_HEIGHT, 16)];
#define gBottleGlassTex_WIDTH 16
#define gBottleGlassTex_HEIGHT 16
extern u64 gBottleGlassTex[TEX_LEN(u64, gBottleGlassTex_WIDTH, gBottleGlassTex_HEIGHT, 16)];
#define gDekuStickTex_WIDTH 8
#define gDekuStickTex_HEIGHT 8
extern u64 gDekuStickTex[TEX_LEN(u64, gDekuStickTex_WIDTH, gDekuStickTex_HEIGHT, 8)];
#define gLinkHairTex_WIDTH 16
#define gLinkHairTex_HEIGHT 16
extern u64 gLinkHairTex[TEX_LEN(u64, gLinkHairTex_WIDTH, gLinkHairTex_HEIGHT, 16)];
#define gLinkTunic1Tex_WIDTH 16
#define gLinkTunic1Tex_HEIGHT 16
extern u64 gLinkTunic1Tex[TEX_LEN(u64, gLinkTunic1Tex_WIDTH, gLinkTunic1Tex_HEIGHT, 8)];
#define gLinkTunic2Tex_WIDTH 16
#define gLinkTunic2Tex_HEIGHT 32
extern u64 gLinkTunic2Tex[TEX_LEN(u64, gLinkTunic2Tex_WIDTH, gLinkTunic2Tex_HEIGHT, 8)];
#define gLinkTunic3Tex_WIDTH 16
#define gLinkTunic3Tex_HEIGHT 16
extern u64 gLinkTunic3Tex[TEX_LEN(u64, gLinkTunic3Tex_WIDTH, gLinkTunic3Tex_HEIGHT, 8)];
extern Vec3s gLinkPauseChildJointTable[];
extern Vec3s gLinkPauseChildDekuShieldJointTable[];
extern Vec3s gLinkPauseAdultBgsJointTable[];
extern Vec3s gLinkPauseAdultJointTable[];
extern Vec3s gLinkPauseAdultShieldJointTable[];
extern LinkAnimationHeader gPlayerAnim_clink_demo_DDbox_open;
extern LinkAnimationHeader gPlayerAnim_clink_demo_Tbox_open;
extern LinkAnimationHeader gPlayerAnim_clink_demo_atozusari;
extern LinkAnimationHeader gPlayerAnim_clink_demo_bashi;
extern LinkAnimationHeader gPlayerAnim_clink_demo_doorA_link;
extern LinkAnimationHeader gPlayerAnim_clink_demo_doorB_link;
extern LinkAnimationHeader gPlayerAnim_clink_demo_futtobi;
extern LinkAnimationHeader gPlayerAnim_clink_demo_get1;
extern LinkAnimationHeader gPlayerAnim_clink_demo_get2;
extern LinkAnimationHeader gPlayerAnim_clink_demo_get3;
extern LinkAnimationHeader gPlayerAnim_clink_demo_goto_future;
extern LinkAnimationHeader gPlayerAnim_clink_demo_koutai;
extern LinkAnimationHeader gPlayerAnim_clink_demo_koutai_kennuki;
extern LinkAnimationHeader gPlayerAnim_clink_demo_koutai_wait;
extern LinkAnimationHeader gPlayerAnim_clink_demo_mimawasi;
extern LinkAnimationHeader gPlayerAnim_clink_demo_mimawasi_wait;
extern LinkAnimationHeader gPlayerAnim_clink_demo_miokuri;
extern LinkAnimationHeader gPlayerAnim_clink_demo_miokuri_wait;
extern LinkAnimationHeader gPlayerAnim_clink_demo_nozoki;
extern LinkAnimationHeader gPlayerAnim_clink_demo_return_to_future;
extern LinkAnimationHeader gPlayerAnim_clink_demo_standup;
extern LinkAnimationHeader gPlayerAnim_clink_demo_standup_wait;
extern LinkAnimationHeader gPlayerAnim_clink_normal_climb_endAL;
extern LinkAnimationHeader gPlayerAnim_clink_normal_climb_endAR;
extern LinkAnimationHeader gPlayerAnim_clink_normal_climb_endBL;
extern LinkAnimationHeader gPlayerAnim_clink_normal_climb_endBR;
extern LinkAnimationHeader gPlayerAnim_clink_normal_climb_startA;
extern LinkAnimationHeader gPlayerAnim_clink_normal_climb_startB;
extern LinkAnimationHeader gPlayerAnim_clink_normal_climb_upL;
extern LinkAnimationHeader gPlayerAnim_clink_normal_climb_upR;
extern LinkAnimationHeader gPlayerAnim_clink_normal_defense_ALL;
extern LinkAnimationHeader gPlayerAnim_clink_op3_negaeri;
extern LinkAnimationHeader gPlayerAnim_clink_op3_okiagari;
extern LinkAnimationHeader gPlayerAnim_clink_op3_tatiagari;
extern LinkAnimationHeader gPlayerAnim_clink_op3_wait1;
extern LinkAnimationHeader gPlayerAnim_clink_op3_wait2;
extern LinkAnimationHeader gPlayerAnim_clink_op3_wait3;
extern LinkAnimationHeader gPlayerAnim_d_link_imanodare;
extern LinkAnimationHeader gPlayerAnim_d_link_orooro;
extern LinkAnimationHeader gPlayerAnim_d_link_orowait;
extern LinkAnimationHeader gPlayerAnim_demo_link_nwait;
extern LinkAnimationHeader gPlayerAnim_demo_link_orosuu;
extern LinkAnimationHeader gPlayerAnim_demo_link_tewatashi;
extern LinkAnimationHeader gPlayerAnim_demo_link_twait;
extern LinkAnimationHeader gPlayerAnim_kolink_odoroki_demo;
extern LinkAnimationHeader gPlayerAnim_link_anchor_LLside_kiru_endL;
extern LinkAnimationHeader gPlayerAnim_link_anchor_LLside_kiru_finsh_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_LRside_kiru_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_LRside_kiru_finsh_endL;
extern LinkAnimationHeader gPlayerAnim_link_anchor_Lnormal_kiru_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_Lnormal_kiru_finsh_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_Lpierce_kiru_endL;
extern LinkAnimationHeader gPlayerAnim_link_anchor_Lpierce_kiru_finsh_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_Lrolling_kiru_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_Lside_kiru_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_Lside_kiru_finsh_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_Rside_kiru_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_Rside_kiru_finsh_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_anchor2fighter;
extern LinkAnimationHeader gPlayerAnim_link_anchor_back_brake;
extern LinkAnimationHeader gPlayerAnim_link_anchor_back_hitR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_back_walk;
extern LinkAnimationHeader gPlayerAnim_link_anchor_bom_side_walkL;
extern LinkAnimationHeader gPlayerAnim_link_anchor_bom_side_walkR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_defense_hit;
extern LinkAnimationHeader gPlayerAnim_link_anchor_defense_long_hitL;
extern LinkAnimationHeader gPlayerAnim_link_anchor_defense_long_hitR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_front_hitR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_jump_kiru_finsh_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_landingR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_normal_kiru_finsh_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_pierce_kiru_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_pierce_kiru_finsh_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_power_kiru_wait_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_rolling_kiru_endR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_side_walkL;
extern LinkAnimationHeader gPlayerAnim_link_anchor_side_walkR;
extern LinkAnimationHeader gPlayerAnim_002578;
extern LinkAnimationHeader gPlayerAnim_link_anchor_waitL2defense;
extern LinkAnimationHeader gPlayerAnim_link_anchor_waitL2defense_long;
extern LinkAnimationHeader gPlayerAnim_link_anchor_waitL;
extern LinkAnimationHeader gPlayerAnim_link_anchor_waitL_defense;
extern LinkAnimationHeader gPlayerAnim_link_anchor_waitL_defense_wait;
extern LinkAnimationHeader gPlayerAnim_0025A8;
extern LinkAnimationHeader gPlayerAnim_link_anchor_waitL_pierce_kiru;
extern LinkAnimationHeader gPlayerAnim_0025B8;
extern LinkAnimationHeader gPlayerAnim_link_anchor_waitR2defense;
extern LinkAnimationHeader gPlayerAnim_link_anchor_waitR2defense_long;
extern LinkAnimationHeader gPlayerAnim_link_anchor_waitR;
extern LinkAnimationHeader gPlayerAnim_link_anchor_waitR_defense;
extern LinkAnimationHeader gPlayerAnim_link_anchor_waitR_defense_wait;
extern LinkAnimationHeader gPlayerAnim_0025E8;
extern LinkAnimationHeader gPlayerAnim_link_anchor_waitR_pierce_kiru;
extern LinkAnimationHeader gPlayerAnim_link_boom_catch;
extern LinkAnimationHeader gPlayerAnim_link_boom_throwL;
extern LinkAnimationHeader gPlayerAnim_link_boom_throwR;
extern LinkAnimationHeader gPlayerAnim_002610;
extern LinkAnimationHeader gPlayerAnim_link_boom_throw_side_walkL;
extern LinkAnimationHeader gPlayerAnim_link_boom_throw_side_walkR;
extern LinkAnimationHeader gPlayerAnim_link_boom_throw_wait2waitR;
extern LinkAnimationHeader gPlayerAnim_link_boom_throw_waitL;
extern LinkAnimationHeader gPlayerAnim_link_boom_throw_waitR;
extern LinkAnimationHeader gPlayerAnim_link_bottle_bug_in;
extern LinkAnimationHeader gPlayerAnim_link_bottle_bug_miss;
extern LinkAnimationHeader gPlayerAnim_link_bottle_bug_out;
extern LinkAnimationHeader gPlayerAnim_link_bottle_drink_demo;
extern LinkAnimationHeader gPlayerAnim_link_bottle_drink_demo_end;
extern LinkAnimationHeader gPlayerAnim_link_bottle_drink_demo_start;
extern LinkAnimationHeader gPlayerAnim_link_bottle_drink_demo_wait;
extern LinkAnimationHeader gPlayerAnim_link_bottle_fish_in;
extern LinkAnimationHeader gPlayerAnim_link_bottle_fish_miss;
extern LinkAnimationHeader gPlayerAnim_link_bottle_fish_out;
extern LinkAnimationHeader gPlayerAnim_link_bottle_read;
extern LinkAnimationHeader gPlayerAnim_link_bottle_read_end;
extern LinkAnimationHeader gPlayerAnim_link_bow_bow_ready;
extern LinkAnimationHeader gPlayerAnim_link_bow_bow_shoot;
extern LinkAnimationHeader gPlayerAnim_link_bow_bow_shoot_end;
extern LinkAnimationHeader gPlayerAnim_link_bow_bow_shoot_next;
extern LinkAnimationHeader gPlayerAnim_link_bow_bow_wait;
extern LinkAnimationHeader gPlayerAnim_link_bow_defense;
extern LinkAnimationHeader gPlayerAnim_link_bow_defense_wait;
extern LinkAnimationHeader gPlayerAnim_link_bow_side_runL;
extern LinkAnimationHeader gPlayerAnim_link_bow_side_runR;
extern LinkAnimationHeader gPlayerAnim_link_bow_side_walk;
extern LinkAnimationHeader gPlayerAnim_link_bow_walk2ready;
extern LinkAnimationHeader gPlayerAnim_link_child_tunnel_door;
extern LinkAnimationHeader gPlayerAnim_link_child_tunnel_end;
extern LinkAnimationHeader gPlayerAnim_link_child_tunnel_start;
extern LinkAnimationHeader gPlayerAnim_link_demo_DDbox_open;
extern LinkAnimationHeader gPlayerAnim_link_demo_Tbox_open;
extern LinkAnimationHeader gPlayerAnim_link_demo_back_to_past;
extern LinkAnimationHeader gPlayerAnim_link_demo_baru_op1;
extern LinkAnimationHeader gPlayerAnim_link_demo_baru_op2;
extern LinkAnimationHeader gPlayerAnim_link_demo_baru_op3;
extern LinkAnimationHeader gPlayerAnim_link_demo_bikkuri;
extern LinkAnimationHeader gPlayerAnim_link_demo_doorA_link;
extern LinkAnimationHeader gPlayerAnim_link_demo_doorA_link_free;
extern LinkAnimationHeader gPlayerAnim_link_demo_doorB_link;
extern LinkAnimationHeader gPlayerAnim_link_demo_doorB_link_free;
extern LinkAnimationHeader gPlayerAnim_link_demo_furimuki2;
extern LinkAnimationHeader gPlayerAnim_link_demo_furimuki2_wait;
extern LinkAnimationHeader gPlayerAnim_link_demo_furimuki;
extern LinkAnimationHeader gPlayerAnim_link_demo_get_itemA;
extern LinkAnimationHeader gPlayerAnim_link_demo_get_itemB;
extern LinkAnimationHeader gPlayerAnim_link_demo_goma_furimuki;
extern LinkAnimationHeader gPlayerAnim_link_demo_gurad;
extern LinkAnimationHeader gPlayerAnim_link_demo_gurad_wait;
extern LinkAnimationHeader gPlayerAnim_link_demo_jibunmiru;
extern LinkAnimationHeader gPlayerAnim_link_demo_kakeyori;
extern LinkAnimationHeader gPlayerAnim_link_demo_kakeyori_mimawasi;
extern LinkAnimationHeader gPlayerAnim_link_demo_kakeyori_miokuri;
extern LinkAnimationHeader gPlayerAnim_link_demo_kakeyori_miokuri_wait;
extern LinkAnimationHeader gPlayerAnim_link_demo_kakeyori_wait;
extern LinkAnimationHeader gPlayerAnim_link_demo_kaoage;
extern LinkAnimationHeader gPlayerAnim_link_demo_kaoage_wait;
extern LinkAnimationHeader gPlayerAnim_link_demo_kenmiru1;
extern LinkAnimationHeader gPlayerAnim_link_demo_kenmiru1_wait;
extern LinkAnimationHeader gPlayerAnim_link_demo_kenmiru2;
extern LinkAnimationHeader gPlayerAnim_link_demo_kenmiru2_modori;
extern LinkAnimationHeader gPlayerAnim_link_demo_kenmiru2_wait;
extern LinkAnimationHeader gPlayerAnim_link_demo_kousan;
extern LinkAnimationHeader gPlayerAnim_link_demo_look_hand;
extern LinkAnimationHeader gPlayerAnim_link_demo_look_hand_wait;
extern LinkAnimationHeader gPlayerAnim_link_demo_nozokikomi;
extern LinkAnimationHeader gPlayerAnim_link_demo_nozokikomi_wait;
extern LinkAnimationHeader gPlayerAnim_link_demo_return_to_past;
extern LinkAnimationHeader gPlayerAnim_002840;
extern LinkAnimationHeader gPlayerAnim_link_demo_sita_wait;
extern LinkAnimationHeader gPlayerAnim_link_demo_ue;
extern LinkAnimationHeader gPlayerAnim_link_demo_ue_wait;
extern LinkAnimationHeader gPlayerAnim_link_demo_warp;
extern LinkAnimationHeader gPlayerAnim_link_demo_zeldamiru;
extern LinkAnimationHeader gPlayerAnim_link_demo_zeldamiru_wait;
extern LinkAnimationHeader gPlayerAnim_link_derth_rebirth;
extern LinkAnimationHeader gPlayerAnim_link_fighter_LLside_kiru;
extern LinkAnimationHeader gPlayerAnim_link_fighter_LLside_kiru_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_LLside_kiru_finsh;
extern LinkAnimationHeader gPlayerAnim_link_fighter_LLside_kiru_finsh_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_LRside_kiru;
extern LinkAnimationHeader gPlayerAnim_link_fighter_LRside_kiru_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_LRside_kiru_finsh;
extern LinkAnimationHeader gPlayerAnim_link_fighter_LRside_kiru_finsh_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lnormal_kiru;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lnormal_kiru_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lnormal_kiru_finsh;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lnormal_kiru_finsh_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lpierce_kiru;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lpierce_kiru_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lpierce_kiru_finsh;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lpierce_kiru_finsh_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lpower_jump_kiru;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lpower_jump_kiru_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lpower_jump_kiru_hit;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lpower_kiru_side_walk;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lpower_kiru_start;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lpower_kiru_wait;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lpower_kiru_wait_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lpower_kiru_walk;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lrolling_kiru;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lrolling_kiru_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lside_jump;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lside_jump_endL;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lside_jump_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lside_kiru;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lside_kiru_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lside_kiru_finsh;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Lside_kiru_finsh_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Rside_jump;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Rside_jump_endR;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Rside_jump_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Rside_kiru;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Rside_kiru_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Rside_kiru_finsh;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Rside_kiru_finsh_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Wrolling_kiru;
extern LinkAnimationHeader gPlayerAnim_link_fighter_Wrolling_kiru_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_backturn_jump;
extern LinkAnimationHeader gPlayerAnim_link_fighter_backturn_jump_endR;
extern LinkAnimationHeader gPlayerAnim_link_fighter_backturn_jump_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_damage_run;
extern LinkAnimationHeader gPlayerAnim_link_fighter_damage_run_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_defense;
extern LinkAnimationHeader gPlayerAnim_link_fighter_defense_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_defense_long_hit;
extern LinkAnimationHeader gPlayerAnim_link_fighter_defense_long_wait;
extern LinkAnimationHeader gPlayerAnim_link_fighter_defense_wait;
extern LinkAnimationHeader gPlayerAnim_link_fighter_fighter2long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_front_jump;
extern LinkAnimationHeader gPlayerAnim_link_fighter_front_jump_endR;
extern LinkAnimationHeader gPlayerAnim_link_fighter_front_jump_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_heavy_run_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_jump_kiru;
extern LinkAnimationHeader gPlayerAnim_link_fighter_jump_kiru_finsh;
extern LinkAnimationHeader gPlayerAnim_link_fighter_jump_kiru_finsh_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_jump_rollkiru;
extern LinkAnimationHeader gPlayerAnim_link_fighter_landing_roll_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_normal2fighter;
extern LinkAnimationHeader gPlayerAnim_002A78;
extern LinkAnimationHeader gPlayerAnim_link_fighter_normal_kiru;
extern LinkAnimationHeader gPlayerAnim_link_fighter_normal_kiru_endR;
extern LinkAnimationHeader gPlayerAnim_link_fighter_normal_kiru_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_normal_kiru_finsh;
extern LinkAnimationHeader gPlayerAnim_link_fighter_normal_kiru_finsh_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_pierce_kiru;
extern LinkAnimationHeader gPlayerAnim_link_fighter_pierce_kiru_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_pierce_kiru_finsh;
extern LinkAnimationHeader gPlayerAnim_link_fighter_pierce_kiru_finsh_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_power_jump_kiru_end;
extern LinkAnimationHeader gPlayerAnim_002AD0;
extern LinkAnimationHeader gPlayerAnim_link_fighter_power_kiru_side_walk;
extern LinkAnimationHeader gPlayerAnim_link_fighter_power_kiru_startL;
extern LinkAnimationHeader gPlayerAnim_link_fighter_power_kiru_start;
extern LinkAnimationHeader gPlayerAnim_link_fighter_power_kiru_wait;
extern LinkAnimationHeader gPlayerAnim_link_fighter_power_kiru_wait_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_power_kiru_walk;
extern LinkAnimationHeader gPlayerAnim_link_fighter_reboundR;
extern LinkAnimationHeader gPlayerAnim_link_fighter_rebound;
extern LinkAnimationHeader gPlayerAnim_link_fighter_rebound_longR;
extern LinkAnimationHeader gPlayerAnim_link_fighter_rebound_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_rolling_kiru;
extern LinkAnimationHeader gPlayerAnim_link_fighter_rolling_kiru_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_run;
extern LinkAnimationHeader gPlayerAnim_link_fighter_run_long;
extern LinkAnimationHeader gPlayerAnim_002B48;
extern LinkAnimationHeader gPlayerAnim_002B50;
extern LinkAnimationHeader gPlayerAnim_link_fighter_side_walkL_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_side_walkR_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_side_walk_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_turn_kiruL;
extern LinkAnimationHeader gPlayerAnim_link_fighter_turn_kiruL_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_turn_kiruR;
extern LinkAnimationHeader gPlayerAnim_link_fighter_turn_kiruR_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_upper_kiruR;
extern LinkAnimationHeader gPlayerAnim_link_fighter_upper_pierce_kiru;
extern LinkAnimationHeader gPlayerAnim_link_fighter_upper_pierce_kiru_end;
extern LinkAnimationHeader gPlayerAnim_link_fighter_wait2waitL_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_wait2waitR_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_waitL2wait_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_waitL_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_waitR2wait_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_waitR_long;
extern LinkAnimationHeader gPlayerAnim_002BD8;
extern LinkAnimationHeader gPlayerAnim_link_fighter_wait_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_walk_endL_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_walk_endR_long;
extern LinkAnimationHeader gPlayerAnim_link_fighter_walk_long;
extern LinkAnimationHeader gPlayerAnim_link_fishing_fish_catch;
extern LinkAnimationHeader gPlayerAnim_link_fishing_fish_catch_end;
extern LinkAnimationHeader gPlayerAnim_link_fishing_reel_down;
extern LinkAnimationHeader gPlayerAnim_link_fishing_reel_left;
extern LinkAnimationHeader gPlayerAnim_link_fishing_reel_right;
extern LinkAnimationHeader gPlayerAnim_link_fishing_reel_up;
extern LinkAnimationHeader gPlayerAnim_link_fishing_throw;
extern LinkAnimationHeader gPlayerAnim_link_fishing_wait;
extern LinkAnimationHeader gPlayerAnim_link_hammer_hit;
extern LinkAnimationHeader gPlayerAnim_link_hammer_hit_endR;
extern LinkAnimationHeader gPlayerAnim_link_hammer_hit_end;
extern LinkAnimationHeader gPlayerAnim_link_hammer_long2free;
extern LinkAnimationHeader gPlayerAnim_link_hammer_long2long;
extern LinkAnimationHeader gPlayerAnim_link_hammer_normal2long;
extern LinkAnimationHeader gPlayerAnim_link_hammer_side_hit;
extern LinkAnimationHeader gPlayerAnim_link_hammer_side_hit_endR;
extern LinkAnimationHeader gPlayerAnim_link_hammer_side_hit_end;
extern LinkAnimationHeader gPlayerAnim_link_hatto_demo;
extern LinkAnimationHeader gPlayerAnim_link_hook_fly_start;
extern LinkAnimationHeader gPlayerAnim_link_hook_fly_wait;
extern LinkAnimationHeader gPlayerAnim_link_hook_shot_ready;
extern LinkAnimationHeader gPlayerAnim_link_hook_side_runL;
extern LinkAnimationHeader gPlayerAnim_link_hook_side_runR;
extern LinkAnimationHeader gPlayerAnim_link_hook_side_walk;
extern LinkAnimationHeader gPlayerAnim_link_hook_wait;
extern LinkAnimationHeader gPlayerAnim_link_hook_walk2ready;
extern LinkAnimationHeader gPlayerAnim_link_last_hit_motion1;
extern LinkAnimationHeader gPlayerAnim_link_last_hit_motion2;
extern LinkAnimationHeader gPlayerAnim_link_magic_honoo1;
extern LinkAnimationHeader gPlayerAnim_link_magic_honoo2;
extern LinkAnimationHeader gPlayerAnim_link_magic_honoo3;
extern LinkAnimationHeader gPlayerAnim_link_magic_kaze1;
extern LinkAnimationHeader gPlayerAnim_link_magic_kaze2;
extern LinkAnimationHeader gPlayerAnim_link_magic_kaze3;
extern LinkAnimationHeader gPlayerAnim_link_magic_tamashii1;
extern LinkAnimationHeader gPlayerAnim_link_magic_tamashii2;
extern LinkAnimationHeader gPlayerAnim_link_magic_tamashii3;
extern LinkAnimationHeader gPlayerAnim_link_magic_tame;
extern LinkAnimationHeader gPlayerAnim_link_magic_tame_kaijyo;
extern LinkAnimationHeader gPlayerAnim_link_normal_100step_up;
extern LinkAnimationHeader gPlayerAnim_link_normal_150step_up;
extern LinkAnimationHeader gPlayerAnim_link_normal_250jump_start;
extern LinkAnimationHeader gPlayerAnim_002D50;
extern LinkAnimationHeader gPlayerAnim_link_normal_45_turn;
extern LinkAnimationHeader gPlayerAnim_link_normal_45_turn_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_Fclimb_hold2upL;
extern LinkAnimationHeader gPlayerAnim_link_normal_Fclimb_sideL;
extern LinkAnimationHeader gPlayerAnim_link_normal_Fclimb_sideR;
extern LinkAnimationHeader gPlayerAnim_link_normal_Fclimb_startA;
extern LinkAnimationHeader gPlayerAnim_link_normal_Fclimb_startB;
extern LinkAnimationHeader gPlayerAnim_link_normal_Fclimb_upL;
extern LinkAnimationHeader gPlayerAnim_link_normal_Fclimb_upR;
extern LinkAnimationHeader gPlayerAnim_link_normal_back_brake;
extern LinkAnimationHeader gPlayerAnim_link_normal_back_brake_end;
extern LinkAnimationHeader gPlayerAnim_link_normal_back_downA;
extern LinkAnimationHeader gPlayerAnim_link_normal_back_downB;
extern LinkAnimationHeader gPlayerAnim_link_normal_back_down_wake;
extern LinkAnimationHeader gPlayerAnim_link_normal_back_hit;
extern LinkAnimationHeader gPlayerAnim_link_normal_back_run;
extern LinkAnimationHeader gPlayerAnim_link_normal_back_shitR;
extern LinkAnimationHeader gPlayerAnim_link_normal_back_shit;
extern LinkAnimationHeader gPlayerAnim_link_normal_back_walk;
extern LinkAnimationHeader gPlayerAnim_link_normal_backspace;
extern LinkAnimationHeader gPlayerAnim_link_normal_box_kick;
extern LinkAnimationHeader gPlayerAnim_link_normal_carryB;
extern LinkAnimationHeader gPlayerAnim_link_normal_carryB_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_carryB_wait;
extern LinkAnimationHeader gPlayerAnim_link_normal_check;
extern LinkAnimationHeader gPlayerAnim_link_normal_check_end;
extern LinkAnimationHeader gPlayerAnim_link_normal_check_end_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_check_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_check_wait;
extern LinkAnimationHeader gPlayerAnim_link_normal_check_wait_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_climb_down;
extern LinkAnimationHeader gPlayerAnim_link_normal_climb_endAL;
extern LinkAnimationHeader gPlayerAnim_link_normal_climb_endAR;
extern LinkAnimationHeader gPlayerAnim_link_normal_climb_endBL;
extern LinkAnimationHeader gPlayerAnim_link_normal_climb_endBR;
extern LinkAnimationHeader gPlayerAnim_link_normal_climb_startA;
extern LinkAnimationHeader gPlayerAnim_link_normal_climb_startB;
extern LinkAnimationHeader gPlayerAnim_link_normal_climb_upL;
extern LinkAnimationHeader gPlayerAnim_link_normal_climb_upR;
extern LinkAnimationHeader gPlayerAnim_link_normal_climb_up;
extern LinkAnimationHeader gPlayerAnim_link_normal_damage_run_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_defense;
extern LinkAnimationHeader gPlayerAnim_link_normal_defense_end;
extern LinkAnimationHeader gPlayerAnim_link_normal_defense_end_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_defense_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_defense_hit;
extern LinkAnimationHeader gPlayerAnim_link_normal_defense_kiru;
extern LinkAnimationHeader gPlayerAnim_link_normal_defense_wait;
extern LinkAnimationHeader gPlayerAnim_link_normal_defense_wait_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_down_slope_slip;
extern LinkAnimationHeader gPlayerAnim_link_normal_down_slope_slip_end;
extern LinkAnimationHeader gPlayerAnim_link_normal_down_slope_slip_end_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_down_slope_slip_end_long;
extern LinkAnimationHeader gPlayerAnim_link_normal_electric_shock;
extern LinkAnimationHeader gPlayerAnim_link_normal_electric_shock_end;
extern LinkAnimationHeader gPlayerAnim_link_normal_fall;
extern LinkAnimationHeader gPlayerAnim_link_normal_fall_up;
extern LinkAnimationHeader gPlayerAnim_link_normal_fall_up_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_fall_wait;
extern LinkAnimationHeader gPlayerAnim_link_normal_fighter2free;
extern LinkAnimationHeader gPlayerAnim_link_normal_free2bom;
extern LinkAnimationHeader gPlayerAnim_link_normal_free2fighter_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_free2freeB;
extern LinkAnimationHeader gPlayerAnim_link_normal_free2free;
extern LinkAnimationHeader gPlayerAnim_link_normal_front_downA;
extern LinkAnimationHeader gPlayerAnim_link_normal_front_downB;
extern LinkAnimationHeader gPlayerAnim_link_normal_front_down_wake;
extern LinkAnimationHeader gPlayerAnim_link_normal_front_hit;
extern LinkAnimationHeader gPlayerAnim_link_normal_front_shitR;
extern LinkAnimationHeader gPlayerAnim_link_normal_front_shit;
extern LinkAnimationHeader gPlayerAnim_link_normal_give_other;
extern LinkAnimationHeader gPlayerAnim_link_normal_hang_up_down;
extern LinkAnimationHeader gPlayerAnim_link_normal_heavy_carry;
extern LinkAnimationHeader gPlayerAnim_link_normal_heavy_carry_end;
extern LinkAnimationHeader gPlayerAnim_link_normal_heavy_run;
extern LinkAnimationHeader gPlayerAnim_link_normal_heavy_run_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_hip_down;
extern LinkAnimationHeader gPlayerAnim_link_normal_hip_down_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_hip_down_long;
extern LinkAnimationHeader gPlayerAnim_link_normal_ice_down;
extern LinkAnimationHeader gPlayerAnim_link_normal_jump2landing;
extern LinkAnimationHeader gPlayerAnim_link_normal_jump;
extern LinkAnimationHeader gPlayerAnim_link_normal_jump_climb_hold;
extern LinkAnimationHeader gPlayerAnim_link_normal_jump_climb_hold_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_jump_climb_up;
extern LinkAnimationHeader gPlayerAnim_link_normal_jump_climb_up_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_jump_climb_wait;
extern LinkAnimationHeader gPlayerAnim_link_normal_jump_climb_wait_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_jump_up;
extern LinkAnimationHeader gPlayerAnim_link_normal_landing;
extern LinkAnimationHeader gPlayerAnim_link_normal_landing_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_landing_roll;
extern LinkAnimationHeader gPlayerAnim_link_normal_landing_roll_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_landing_wait;
extern LinkAnimationHeader gPlayerAnim_link_normal_light_bom;
extern LinkAnimationHeader gPlayerAnim_link_normal_light_bom_end;
extern LinkAnimationHeader gPlayerAnim_link_normal_long2bom;
extern LinkAnimationHeader gPlayerAnim_link_normal_nocarry_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_nocarry_free_end;
extern LinkAnimationHeader gPlayerAnim_link_normal_nocarry_free_wait;
extern LinkAnimationHeader gPlayerAnim_link_normal_normal2bom;
extern LinkAnimationHeader gPlayerAnim_link_normal_normal2fighter;
extern LinkAnimationHeader gPlayerAnim_link_normal_normal2fighter_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_normal2free;
extern LinkAnimationHeader gPlayerAnim_link_normal_okarina_end;
extern LinkAnimationHeader gPlayerAnim_link_normal_okarina_start;
extern LinkAnimationHeader gPlayerAnim_link_normal_okarina_swing;
extern LinkAnimationHeader gPlayerAnim_link_normal_pull_end;
extern LinkAnimationHeader gPlayerAnim_link_normal_pull_end_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_pull_start;
extern LinkAnimationHeader gPlayerAnim_link_normal_pull_start_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_pulling;
extern LinkAnimationHeader gPlayerAnim_link_normal_pulling_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_push_end;
extern LinkAnimationHeader gPlayerAnim_link_normal_push_fall;
extern LinkAnimationHeader gPlayerAnim_link_normal_push_start;
extern LinkAnimationHeader gPlayerAnim_link_normal_push_wait;
extern LinkAnimationHeader gPlayerAnim_link_normal_push_wait_end;
extern LinkAnimationHeader gPlayerAnim_link_normal_pushing;
extern LinkAnimationHeader gPlayerAnim_link_normal_put;
extern LinkAnimationHeader gPlayerAnim_link_normal_put_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_re_dead_attack;
extern LinkAnimationHeader gPlayerAnim_link_normal_re_dead_attack_wait;
extern LinkAnimationHeader gPlayerAnim_link_normal_rebound;
extern LinkAnimationHeader gPlayerAnim_link_normal_run;
extern LinkAnimationHeader gPlayerAnim_link_normal_run_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_run_jump;
extern LinkAnimationHeader gPlayerAnim_link_normal_run_jump_end;
extern LinkAnimationHeader gPlayerAnim_link_normal_run_jump_water_fall;
extern LinkAnimationHeader gPlayerAnim_link_normal_run_jump_water_fall_wait;
extern LinkAnimationHeader gPlayerAnim_link_normal_short_landing;
extern LinkAnimationHeader gPlayerAnim_link_normal_short_landing_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_side_walkL_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_side_walkR_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_side_walk;
extern LinkAnimationHeader gPlayerAnim_link_normal_side_walk_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_take_out;
extern LinkAnimationHeader gPlayerAnim_link_normal_talk_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_talk_free_wait;
extern LinkAnimationHeader gPlayerAnim_link_normal_talk_navi;
extern LinkAnimationHeader gPlayerAnim_link_normal_talk_navi_wait;
extern LinkAnimationHeader gPlayerAnim_link_normal_throw;
extern LinkAnimationHeader gPlayerAnim_link_normal_throw_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_up_slope_slip;
extern LinkAnimationHeader gPlayerAnim_link_normal_up_slope_slip_end;
extern LinkAnimationHeader gPlayerAnim_link_normal_up_slope_slip_end_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_up_slope_slip_end_long;
extern LinkAnimationHeader gPlayerAnim_link_normal_wait2waitL;
extern LinkAnimationHeader gPlayerAnim_link_normal_wait2waitR;
extern LinkAnimationHeader gPlayerAnim_link_normal_waitF_typeA_20f;
extern LinkAnimationHeader gPlayerAnim_link_normal_waitF_typeB_20f;
extern LinkAnimationHeader gPlayerAnim_link_normal_waitF_typeC_20f;
extern LinkAnimationHeader gPlayerAnim_link_normal_waitL2wait;
extern LinkAnimationHeader gPlayerAnim_link_normal_waitL_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_waitR2wait;
extern LinkAnimationHeader gPlayerAnim_link_normal_waitR_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_wait;
extern LinkAnimationHeader gPlayerAnim_link_normal_wait_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_wait_typeA_20f;
extern LinkAnimationHeader gPlayerAnim_link_normal_wait_typeB_20f;
extern LinkAnimationHeader gPlayerAnim_link_normal_wait_typeC_20f;
extern LinkAnimationHeader gPlayerAnim_link_normal_wakeup;
extern LinkAnimationHeader gPlayerAnim_link_normal_walk;
extern LinkAnimationHeader gPlayerAnim_link_normal_walk_endL;
extern LinkAnimationHeader gPlayerAnim_link_normal_walk_endL_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_walk_endR;
extern LinkAnimationHeader gPlayerAnim_link_normal_walk_endR_free;
extern LinkAnimationHeader gPlayerAnim_link_normal_walk_free;
extern LinkAnimationHeader gPlayerAnim_link_okarina_warp_goal;
extern LinkAnimationHeader gPlayerAnim_link_okiru_demo;
extern LinkAnimationHeader gPlayerAnim_link_shagamu_demo;
extern LinkAnimationHeader gPlayerAnim_link_silver_carry;
extern LinkAnimationHeader gPlayerAnim_link_silver_throw;
extern LinkAnimationHeader gPlayerAnim_link_silver_wait;
extern LinkAnimationHeader gPlayerAnim_link_swimer_Lside_swim;
extern LinkAnimationHeader gPlayerAnim_link_swimer_Rside_swim;
extern LinkAnimationHeader gPlayerAnim_link_swimer_back_swim;
extern LinkAnimationHeader gPlayerAnim_link_swimer_land2swim_wait;
extern LinkAnimationHeader gPlayerAnim_link_swimer_swim_15step_up;
extern LinkAnimationHeader gPlayerAnim_link_swimer_swim;
extern LinkAnimationHeader gPlayerAnim_link_swimer_swim_dead;
extern LinkAnimationHeader gPlayerAnim_link_swimer_swim_deep_end;
extern LinkAnimationHeader gPlayerAnim_link_swimer_swim_deep_start;
extern LinkAnimationHeader gPlayerAnim_link_swimer_swim_down;
extern LinkAnimationHeader gPlayerAnim_link_swimer_swim_get;
extern LinkAnimationHeader gPlayerAnim_link_swimer_swim_hit;
extern LinkAnimationHeader gPlayerAnim_link_swimer_swim_wait;
extern LinkAnimationHeader gPlayerAnim_link_swimer_wait2swim_wait;
extern LinkAnimationHeader gPlayerAnim_link_uma_anim_fastrun;
extern LinkAnimationHeader gPlayerAnim_link_uma_anim_fastrun_muti;
extern LinkAnimationHeader gPlayerAnim_link_uma_anim_jump100;
extern LinkAnimationHeader gPlayerAnim_link_uma_anim_jump200;
extern LinkAnimationHeader gPlayerAnim_link_uma_anim_slowrun;
extern LinkAnimationHeader gPlayerAnim_link_uma_anim_slowrun_muti;
extern LinkAnimationHeader gPlayerAnim_link_uma_anim_stand;
extern LinkAnimationHeader gPlayerAnim_link_uma_anim_stop;
extern LinkAnimationHeader gPlayerAnim_link_uma_anim_walk2;
extern LinkAnimationHeader gPlayerAnim_link_uma_anim_walk;
extern LinkAnimationHeader gPlayerAnim_link_uma_anim_walk_muti;
extern LinkAnimationHeader gPlayerAnim_link_uma_left_down;
extern LinkAnimationHeader gPlayerAnim_link_uma_left_up;
extern LinkAnimationHeader gPlayerAnim_link_uma_right_down;
extern LinkAnimationHeader gPlayerAnim_link_uma_right_up;
extern LinkAnimationHeader gPlayerAnim_link_uma_stop_muti;
extern LinkAnimationHeader gPlayerAnim_link_uma_wait_1;
extern LinkAnimationHeader gPlayerAnim_link_uma_wait_2;
extern LinkAnimationHeader gPlayerAnim_link_uma_wait_3;
extern LinkAnimationHeader gPlayerAnim_link_waitF_heat1_20f;
extern LinkAnimationHeader gPlayerAnim_link_waitF_heat2_20f;
extern LinkAnimationHeader gPlayerAnim_link_waitF_itemA_20f;
extern LinkAnimationHeader gPlayerAnim_link_waitF_itemB_20f;
extern LinkAnimationHeader gPlayerAnim_link_waitF_typeD_20f;
extern LinkAnimationHeader gPlayerAnim_link_wait_heat1_20f;
extern LinkAnimationHeader gPlayerAnim_link_wait_heat2_20f;
extern LinkAnimationHeader gPlayerAnim_link_wait_itemA_20f;
extern LinkAnimationHeader gPlayerAnim_link_wait_itemB_20f;
extern LinkAnimationHeader gPlayerAnim_link_wait_itemC_20f;
extern LinkAnimationHeader gPlayerAnim_link_wait_itemD1_20f;
extern LinkAnimationHeader gPlayerAnim_link_wait_itemD2_20f;
extern LinkAnimationHeader gPlayerAnim_link_wait_typeD_20f;
extern LinkAnimationHeader gPlayerAnim_lkt_nwait;
extern LinkAnimationHeader gPlayerAnim_nw_modoru;
extern LinkAnimationHeader gPlayerAnim_o_get_ato;
extern LinkAnimationHeader gPlayerAnim_o_get_mae;
extern LinkAnimationHeader gPlayerAnim_om_get;
extern LinkAnimationHeader gPlayerAnim_om_get_mae;
extern LinkAnimationHeader gPlayerAnim_sude_nwait;
extern LinkAnimationHeader gPlayerAnim_L_1kyoro;
extern LinkAnimationHeader gPlayerAnim_L_2kyoro;
extern LinkAnimationHeader gPlayerAnim_L_bouzen;
extern LinkAnimationHeader gPlayerAnim_L_hajikareru;
extern LinkAnimationHeader gPlayerAnim_L_kamaeru;
extern LinkAnimationHeader gPlayerAnim_L_ken_miru;
extern LinkAnimationHeader gPlayerAnim_L_kennasi_w;
extern LinkAnimationHeader gPlayerAnim_L_kw;
extern LinkAnimationHeader gPlayerAnim_L_mukinaoru;
extern LinkAnimationHeader gPlayerAnim_L_okarina_get;
extern LinkAnimationHeader gPlayerAnim_L_sagaru;
extern LinkAnimationHeader gPlayerAnim_Link_ha;
extern LinkAnimationHeader gPlayerAnim_Link_m_wait;
extern LinkAnimationHeader gPlayerAnim_Link_miageru;
extern LinkAnimationHeader gPlayerAnim_Link_muku;
extern LinkAnimationHeader gPlayerAnim_Link_otituku_w;
extern LinkAnimationHeader gPlayerAnim_Link_ue_wait;
extern Vtx gDebugPyramidVtx[];
extern Gfx gDebugPyramidDL[6];
#define gDebugCircleTex_WIDTH 16
#define gDebugCircleTex_HEIGHT 16
extern u64 gDebugCircleTex[TEX_LEN(u64, gDebugCircleTex_WIDTH, gDebugCircleTex_HEIGHT, 8)];
#define gDebugBallTex_WIDTH 16
#define gDebugBallTex_HEIGHT 16
extern u64 gDebugBallTex[TEX_LEN(u64, gDebugBallTex_WIDTH, gDebugBallTex_HEIGHT, 8)];
#define gDebugCursorTex_WIDTH 16
#define gDebugCursorTex_HEIGHT 16
extern u64 gDebugCursorTex[TEX_LEN(u64, gDebugCursorTex_WIDTH, gDebugCursorTex_HEIGHT, 8)];
#define gDebugCrossTex_WIDTH 16
#define gDebugCrossTex_HEIGHT 16
extern u64 gDebugCrossTex[TEX_LEN(u64, gDebugCrossTex_WIDTH, gDebugCrossTex_HEIGHT, 8)];
extern Gfx gDebugArrowDL[12];
extern Vtx gDebugArrowVtx[];
extern Gfx gDebugCameraDL[15];
extern Vtx gDebugCameraVtx[];
extern Vtx gDebugCheckeredFloorVtx[];
extern Gfx gDebugCheckeredFloorDL[18];
#define gDebugCheckeredFloorTex_WIDTH 32
#define gDebugCheckeredFloorTex_HEIGHT 32
extern u64 gDebugCheckeredFloorTex[TEX_LEN(u64, gDebugCheckeredFloorTex_WIDTH, gDebugCheckeredFloorTex_HEIGHT, 4)];
extern Vtx gDebugSpriteVtx[];
extern Gfx gDebugSpriteDL[3];
extern s16 gArrow1FrameData[];
extern JointIndex gArrow1JointIndices[];
extern AnimationHeader gArrow1Anim;
extern s16 gArrow2FrameData[];
extern JointIndex gArrow2JointIndices[];
extern AnimationHeader gArrow2Anim;
#define gArrowShaftTex_WIDTH 16
#define gArrowShaftTex_HEIGHT 128
extern u64 gArrowShaftTex[TEX_LEN(u64, gArrowShaftTex_WIDTH, gArrowShaftTex_HEIGHT, 16)];
#define gArrowFletchingTex_WIDTH 32
#define gArrowFletchingTex_HEIGHT 16
extern u64 gArrowFletchingTex[TEX_LEN(u64, gArrowFletchingTex_WIDTH, gArrowFletchingTex_HEIGHT, 16)];
extern Vtx gArrowNearVtx[];
extern Gfx gArrowNearDL[60];
extern Vtx gArrowFarVtx[];
extern Gfx gArrowFarDL[52];
extern LodLimb gameplay_keep_005FC0_Limb;
extern LodLimb gameplay_keep_005FD0_Limb;
extern LodLimb gameplay_keep_005FE0_Limb;
extern LodLimb gameplay_keep_005FF0_Limb;
extern void* gArrowLimbs[];
typedef enum gArrowSkelLimb {
    /*  0 */ LIMB_GAMEPLAY_KEEP_006010_NONE,
    /*  1 */ LIMB_GAMEPLAY_KEEP_005FC0,
    /*  2 */ LIMB_GAMEPLAY_KEEP_005FD0,
    /*  3 */ LIMB_GAMEPLAY_KEEP_005FE0,
    /*  4 */ LIMB_GAMEPLAY_KEEP_005FF0,
    /*  5 */ LIMB_GAMEPLAY_KEEP_006010_MAX
} gArrowSkelLimb;
extern SkeletonHeader gArrowSkel;
#define gUnknownEffBlureTex_WIDTH 64
#define gUnknownEffBlureTex_HEIGHT 32
extern u64 gUnknownEffBlureTex[TEX_LEN(u64, gUnknownEffBlureTex_WIDTH, gUnknownEffBlureTex_HEIGHT, 8)];
#define gBombBodyTex_WIDTH 64
#define gBombBodyTex_HEIGHT 64
extern u64 gBombBodyTex[TEX_LEN(u64, gBombBodyTex_WIDTH, gBombBodyTex_HEIGHT, 8)];
extern Vtx gBombBodyVtx[];
extern Gfx gBombBodyDL[17];
#define gBombCapTex_WIDTH 8
#define gBombCapTex_HEIGHT 8
extern u64 gBombCapTex[TEX_LEN(u64, gBombCapTex_WIDTH, gBombCapTex_HEIGHT, 16)];
extern Vtx gBombCapVtx[];
extern Gfx gBombCapDL[24];
#define gBombchuBodyTex_WIDTH 8
#define gBombchuBodyTex_HEIGHT 8
extern u64 gBombchuBodyTex[TEX_LEN(u64, gBombchuBodyTex_WIDTH, gBombchuBodyTex_HEIGHT, 16)];
extern Vtx gBombchuVtx[];
extern Gfx gBombchuDL[45];
#define gEffBombExplosion1Tex_WIDTH 32
#define gEffBombExplosion1Tex_HEIGHT 32
extern u64 gEffBombExplosion1Tex[TEX_LEN(u64, gEffBombExplosion1Tex_WIDTH, gEffBombExplosion1Tex_HEIGHT, 16)];
#define gEffBombExplosion2Tex_WIDTH 32
#define gEffBombExplosion2Tex_HEIGHT 32
extern u64 gEffBombExplosion2Tex[TEX_LEN(u64, gEffBombExplosion2Tex_WIDTH, gEffBombExplosion2Tex_HEIGHT, 16)];
#define gEffBombExplosion3Tex_WIDTH 32
#define gEffBombExplosion3Tex_HEIGHT 32
extern u64 gEffBombExplosion3Tex[TEX_LEN(u64, gEffBombExplosion3Tex_WIDTH, gEffBombExplosion3Tex_HEIGHT, 16)];
#define gEffBombExplosion4Tex_WIDTH 32
#define gEffBombExplosion4Tex_HEIGHT 32
extern u64 gEffBombExplosion4Tex[TEX_LEN(u64, gEffBombExplosion4Tex_WIDTH, gEffBombExplosion4Tex_HEIGHT, 16)];
#define gEffBombExplosion5Tex_WIDTH 32
#define gEffBombExplosion5Tex_HEIGHT 32
extern u64 gEffBombExplosion5Tex[TEX_LEN(u64, gEffBombExplosion5Tex_WIDTH, gEffBombExplosion5Tex_HEIGHT, 16)];
#define gEffBombExplosion6Tex_WIDTH 32
#define gEffBombExplosion6Tex_HEIGHT 32
extern u64 gEffBombExplosion6Tex[TEX_LEN(u64, gEffBombExplosion6Tex_WIDTH, gEffBombExplosion6Tex_HEIGHT, 16)];
#define gEffBombExplosion7Tex_WIDTH 32
#define gEffBombExplosion7Tex_HEIGHT 32
extern u64 gEffBombExplosion7Tex[TEX_LEN(u64, gEffBombExplosion7Tex_WIDTH, gEffBombExplosion7Tex_HEIGHT, 16)];
#define gEffBombExplosion8Tex_WIDTH 32
#define gEffBombExplosion8Tex_HEIGHT 32
extern u64 gEffBombExplosion8Tex[TEX_LEN(u64, gEffBombExplosion8Tex_WIDTH, gEffBombExplosion8Tex_HEIGHT, 16)];
extern Gfx gEffBombExplosion1DL[13];
extern Gfx gEffBombExplosion2DL[11];
extern Gfx gEffBombExplosion3DL[3];
extern Vtx gEffBombExplosionVtx[];
extern Vtx gEffFragments1Vtx[];
extern Gfx gEffFragments1DL[18];
#define gWitheredLeafTex_WIDTH 16
#define gWitheredLeafTex_HEIGHT 16
extern u64 gWitheredLeafTex[TEX_LEN(u64, gWitheredLeafTex_WIDTH, gWitheredLeafTex_HEIGHT, 16)];
extern Vtx gBoomerangVtx[];
extern Gfx gUnknownBlankDL[1];
extern Gfx gBoomerangDL[46];
extern Gfx gBoomerangRefDL[2];
extern Gfx gCompassArrowDL[5];
extern Vtx gCompassArrowVtx[];
extern Vtx gameplay_keep_Vtx_00C880[];
extern Gfx gGameplayKeepDL_C8B0[14];
extern Vtx gLockOnArrowVtx[];
extern Gfx gLockOnArrowDL[34];
#define gHilite3Tex_WIDTH 8
#define gHilite3Tex_HEIGHT 8
extern u64 gHilite3Tex[TEX_LEN(u64, gHilite3Tex_WIDTH, gHilite3Tex_HEIGHT, 8)];
extern Vtx gEffFragments2Vtx[];
extern Gfx gEffFragments2DL[7];
#define gGameplayKeepTex_CE60_WIDTH 32
#define gGameplayKeepTex_CE60_HEIGHT 32
extern u64 gGameplayKeepTex_CE60[TEX_LEN(u64, gGameplayKeepTex_CE60_WIDTH, gGameplayKeepTex_CE60_HEIGHT, 8)];
#define gSelectionCursorTex_WIDTH 16
#define gSelectionCursorTex_HEIGHT 16
extern u64 gSelectionCursorTex[TEX_LEN(u64, gSelectionCursorTex_WIDTH, gSelectionCursorTex_HEIGHT, 4)];
#define gControlStickTex_WIDTH 16
#define gControlStickTex_HEIGHT 16
extern u64 gControlStickTex[TEX_LEN(u64, gControlStickTex_WIDTH, gControlStickTex_HEIGHT, 8)];
#define gArrowCursorTex_WIDTH 16
#define gArrowCursorTex_HEIGHT 24
extern u64 gArrowCursorTex[TEX_LEN(u64, gArrowCursorTex_WIDTH, gArrowCursorTex_HEIGHT, 8)];
extern Vtx gUnusedRockFragmentVtx[];
extern Gfx gUnusedRockFragmentDL[32];
extern Gfx gBoulderFragmentsDL[27];
extern Vtx gBoulderFragmentsVtx[];
#define gRockFragment1Tex_WIDTH 32
#define gRockFragment1Tex_HEIGHT 32
extern u64 gRockFragment1Tex[TEX_LEN(u64, gRockFragment1Tex_WIDTH, gRockFragment1Tex_HEIGHT, 16)];
#define gRockFragment2Tex_WIDTH 32
#define gRockFragment2Tex_HEIGHT 32
extern u64 gRockFragment2Tex[TEX_LEN(u64, gRockFragment2Tex_WIDTH, gRockFragment2Tex_HEIGHT, 16)];
extern s16 gDoorChildOpeningLeftFrameData[];
extern JointIndex gDoorChildOpeningLeftJointIndices[];
extern AnimationHeader gDoorChildOpeningLeftAnim;
extern s16 gDoorChildOpeningRightFrameData[];
extern JointIndex gDoorChildOpeningRightJointIndices[];
extern AnimationHeader gDoorChildOpeningRightAnim;
extern s16 gDoorAdultOpeningLeftFrameData[];
extern JointIndex gDoorAdultOpeningLeftJointIndices[];
extern AnimationHeader gDoorAdultOpeningLeftAnim;
extern Vtx gDoorLeftVtx[];
extern Vtx gDoorRightVtx[];
extern Vtx gDoorFrameVtx[];
extern Gfx gDoorFrameDL[17];
extern Gfx gDoorLeftDL[41];
extern Gfx gDoorRightDL[39];
#define gWoodenDoorTex_WIDTH 32
#define gWoodenDoorTex_HEIGHT 64
extern u64 gWoodenDoorTex[TEX_LEN(u64, gWoodenDoorTex_WIDTH, gWoodenDoorTex_HEIGHT, 16)];
extern StandardLimb gameplay_keep_0103D8_Limb;
extern StandardLimb gameplay_keep_0103E4_Limb;
extern StandardLimb gameplay_keep_0103F0_Limb;
extern StandardLimb gameplay_keep_0103FC_Limb;
extern void* gDoorLimbs[];
typedef enum gDoorSkelLimb {
    /*  0 */ LIMB_GAMEPLAY_KEEP_010418_NONE,
    /*  1 */ LIMB_GAMEPLAY_KEEP_0103D8,
    /*  2 */ LIMB_GAMEPLAY_KEEP_0103E4,
    /*  3 */ LIMB_GAMEPLAY_KEEP_0103F0,
    /*  4 */ LIMB_GAMEPLAY_KEEP_0103FC,
    /*  5 */ LIMB_GAMEPLAY_KEEP_010418_MAX
} gDoorSkelLimb;
extern SkeletonHeader gDoorSkel;
extern s16 gDoorAdultOpeningRightFrameData[];
extern JointIndex gDoorAdultOpeningRightJointIndices[];
extern AnimationHeader gDoorAdultOpeningRightAnim;
extern Gfx gEffDustDL[11];
extern Vtx gEffDustVtx[];
extern Vtx gEffFlashVtx[];
extern Gfx gEffFlash1DL[15];
extern Gfx gEffFlash2DL[16];
#define gFlashTex_WIDTH 64
#define gFlashTex_HEIGHT 64
extern u64 gFlashTex[TEX_LEN(u64, gFlashTex_WIDTH, gFlashTex_HEIGHT, 8)];
#define gTorchFlameTex_WIDTH 64
#define gTorchFlameTex_HEIGHT 32
extern u64 gTorchFlameTex[TEX_LEN(u64, gTorchFlameTex_WIDTH, gTorchFlameTex_HEIGHT, 8)];
#define gEffUnknown1Tex_WIDTH 64
#define gEffUnknown1Tex_HEIGHT 32
extern u64 gEffUnknown1Tex[TEX_LEN(u64, gEffUnknown1Tex_WIDTH, gEffUnknown1Tex_HEIGHT, 8)];
extern Vtx gSpinAttack1Vtx[];
extern Vtx gSpinAttack2Vtx[];
extern Gfx gSpinAttack1DL[36];
extern Gfx gSpinAttack2DL[36];
extern Vtx gSpinAttack3Vtx[];
extern Vtx gSpinAttack4Vtx[];
extern Gfx gSpinAttack3DL[36];
extern Gfx gSpinAttack4DL[36];
#define gFlameWall1Tex_WIDTH 32
#define gFlameWall1Tex_HEIGHT 32
extern u64 gFlameWall1Tex[TEX_LEN(u64, gFlameWall1Tex_WIDTH, gFlameWall1Tex_HEIGHT, 8)];
#define gFlameWall2Tex_WIDTH 32
#define gFlameWall2Tex_HEIGHT 32
extern u64 gFlameWall2Tex[TEX_LEN(u64, gFlameWall2Tex_WIDTH, gFlameWall2Tex_HEIGHT, 8)];
extern Vtx gSpinAttackChargingVtx[];
extern Gfx gSpinAttackChargingDL[29];
#define gEffUnknown2Tex_WIDTH 32
#define gEffUnknown2Tex_HEIGHT 64
extern u64 gEffUnknown2Tex[TEX_LEN(u64, gEffUnknown2Tex_WIDTH, gEffUnknown2Tex_HEIGHT, 8)];
#define gEffUnknown3Tex_WIDTH 32
#define gEffUnknown3Tex_HEIGHT 64
extern u64 gEffUnknown3Tex[TEX_LEN(u64, gEffUnknown3Tex_WIDTH, gEffUnknown3Tex_HEIGHT, 8)];
extern Vtx gUnusedBeamBladeVtx[];
extern Gfx gUnusedBeamBladeDL[37];
extern s16 gFairyFrameData[];
extern JointIndex gFairyJointIndices[];
extern AnimationHeader gFairyAnim;
#define gFairyWingTex_WIDTH 32
#define gFairyWingTex_HEIGHT 64
extern u64 gFairyWingTex[TEX_LEN(u64, gFairyWingTex_WIDTH, gFairyWingTex_HEIGHT, 8)];
extern Vtx gFairyWing1Vtx[];
extern Gfx gFairyWing1DL[17];
extern Vtx gFairyWing2Vtx[];
extern Gfx gFairyWing2DL[17];
extern Vtx gFairyWing3Vtx[];
extern Gfx gFairyWing3DL[17];
extern Vtx gFairyWing4Vtx[];
extern Gfx gFairyWing4DL[17];
extern Vtx gGlowCircleVtx[];
extern Gfx gGlowCircleTextureLoadDL[8];
extern Gfx gGlowCircleDL[4];
extern Gfx gGlowCircleSmallDL[45];
extern Vtx gGlowCircleSmallVtx[];
#define gUnusedFairyWingTex_WIDTH 32
#define gUnusedFairyWingTex_HEIGHT 64
extern u64 gUnusedFairyWingTex[TEX_LEN(u64, gUnusedFairyWingTex_WIDTH, gUnusedFairyWingTex_HEIGHT, 16)];
extern StandardLimb gameplay_keep_016E08_Limb;
extern StandardLimb gameplay_keep_016E14_Limb;
extern StandardLimb gameplay_keep_016E20_Limb;
extern StandardLimb gameplay_keep_016E2C_Limb;
extern StandardLimb gameplay_keep_016E38_Limb;
extern StandardLimb gameplay_keep_016E44_Limb;
extern StandardLimb gameplay_keep_016E50_Limb;
extern StandardLimb gameplay_keep_016E5C_Limb;
extern StandardLimb gameplay_keep_016E68_Limb;
extern StandardLimb gameplay_keep_016E74_Limb;
extern StandardLimb gameplay_keep_016E80_Limb;
extern StandardLimb gameplay_keep_016E8C_Limb;
extern StandardLimb gameplay_keep_016E98_Limb;
extern StandardLimb gameplay_keep_016EA4_Limb;
extern void* gFairyLimbs[];
typedef enum gFairySkelLimb {
    /*  0 */ LIMB_GAMEPLAY_KEEP_016EE8_NONE,
    /*  1 */ LIMB_GAMEPLAY_KEEP_016E08,
    /*  2 */ LIMB_GAMEPLAY_KEEP_016E14,
    /*  3 */ LIMB_GAMEPLAY_KEEP_016E20,
    /*  4 */ LIMB_GAMEPLAY_KEEP_016E2C,
    /*  5 */ LIMB_GAMEPLAY_KEEP_016E38,
    /*  6 */ LIMB_GAMEPLAY_KEEP_016E44,
    /*  7 */ LIMB_GAMEPLAY_KEEP_016E50,
    /*  8 */ LIMB_GAMEPLAY_KEEP_016E5C,
    /*  9 */ LIMB_GAMEPLAY_KEEP_016E68,
    /* 10 */ LIMB_GAMEPLAY_KEEP_016E74,
    /* 11 */ LIMB_GAMEPLAY_KEEP_016E80,
    /* 12 */ LIMB_GAMEPLAY_KEEP_016E8C,
    /* 13 */ LIMB_GAMEPLAY_KEEP_016E98,
    /* 14 */ LIMB_GAMEPLAY_KEEP_016EA4,
    /* 15 */ LIMB_GAMEPLAY_KEEP_016EE8_MAX
} gFairySkelLimb;
extern SkeletonHeader gFairySkel;
#define gUnknownCircle3Tex_WIDTH 16
#define gUnknownCircle3Tex_HEIGHT 16
extern u64 gUnknownCircle3Tex[TEX_LEN(u64, gUnknownCircle3Tex_WIDTH, gUnknownCircle3Tex_HEIGHT, 4)];
#define gUnknownCircle4Tex_WIDTH 16
#define gUnknownCircle4Tex_HEIGHT 16
extern u64 gUnknownCircle4Tex[TEX_LEN(u64, gUnknownCircle4Tex_WIDTH, gUnknownCircle4Tex_HEIGHT, 8)];
#define gHilite4Tex_WIDTH 32
#define gHilite4Tex_HEIGHT 32
extern u64 gHilite4Tex[TEX_LEN(u64, gHilite4Tex_WIDTH, gHilite4Tex_HEIGHT, 16)];
#define gEffUnknown4Tex_WIDTH 32
#define gEffUnknown4Tex_HEIGHT 64
extern u64 gEffUnknown4Tex[TEX_LEN(u64, gEffUnknown4Tex_WIDTH, gEffUnknown4Tex_HEIGHT, 8)];
#define gEffUnknown5Tex_WIDTH 32
#define gEffUnknown5Tex_HEIGHT 64
extern u64 gEffUnknown5Tex[TEX_LEN(u64, gEffUnknown5Tex_WIDTH, gEffUnknown5Tex_HEIGHT, 8)];
extern Vtx gEffFireCircleVtx[];
extern Gfx gEffFireCircleDL[30];
extern s16 gFishOutOfWaterFrameData[];
extern JointIndex gFishOutOfWaterJointIndices[];
extern AnimationHeader gFishOutOfWaterAnim;
extern Vtx gameplay_keep_Vtx_018AB0[];
extern Vtx gameplay_keep_Vtx_018AF0[];
extern Vtx gameplay_keep_Vtx_018BF0[];
extern Gfx gameplay_keep_018D50_DL[20];
extern Gfx gameplay_keep_018DF0_DL[35];
extern Gfx gameplay_keep_018F08_DL[35];
#define gFishTailTex_WIDTH 16
#define gFishTailTex_HEIGHT 16
extern u64 gFishTailTex[TEX_LEN(u64, gFishTailTex_WIDTH, gFishTailTex_HEIGHT, 16)];
#define gFishBodyTex_WIDTH 32
#define gFishBodyTex_HEIGHT 8
extern u64 gFishBodyTex[TEX_LEN(u64, gFishBodyTex_WIDTH, gFishBodyTex_HEIGHT, 16)];
extern StandardLimb gameplay_keep_019420_Limb;
extern StandardLimb gameplay_keep_01942C_Limb;
extern StandardLimb gameplay_keep_019438_Limb;
extern StandardLimb gameplay_keep_019444_Limb;
extern StandardLimb gameplay_keep_019450_Limb;
extern StandardLimb gameplay_keep_01945C_Limb;
extern void* gFishLimbs[];
typedef enum gFishSkelLimb {
    /*  0 */ LIMB_GAMEPLAY_KEEP_019480_NONE,
    /*  1 */ LIMB_GAMEPLAY_KEEP_019420,
    /*  2 */ LIMB_GAMEPLAY_KEEP_01942C,
    /*  3 */ LIMB_GAMEPLAY_KEEP_019438,
    /*  4 */ LIMB_GAMEPLAY_KEEP_019444,
    /*  5 */ LIMB_GAMEPLAY_KEEP_019450,
    /*  6 */ LIMB_GAMEPLAY_KEEP_01945C,
    /*  7 */ LIMB_GAMEPLAY_KEEP_019480_MAX
} gFishSkelLimb;
extern FlexSkeletonHeader gFishSkel;
extern s16 gFishInWaterFrameData[];
extern JointIndex gFishInWaterJointIndices[];
extern AnimationHeader gFishInWaterAnim;
#define gEffShockwaveTex_WIDTH 64
#define gEffShockwaveTex_HEIGHT 64
extern u64 gEffShockwaveTex[TEX_LEN(u64, gEffShockwaveTex_WIDTH, gEffShockwaveTex_HEIGHT, 8)];
extern Gfx gEffShockwaveDL[14];
extern Vtx gGameplayKeepVtx_01A120[];
extern Gfx gEffBubbleDL[15];
extern Vtx gEffBubbleVtx[];
#define gEffFireFootprint1Tex_WIDTH 32
#define gEffFireFootprint1Tex_HEIGHT 32
extern u64 gEffFireFootprint1Tex[TEX_LEN(u64, gEffFireFootprint1Tex_WIDTH, gEffFireFootprint1Tex_HEIGHT, 8)];
#define gEffFireFootprint2Tex_WIDTH 32
#define gEffFireFootprint2Tex_HEIGHT 32
extern u64 gEffFireFootprint2Tex[TEX_LEN(u64, gEffFireFootprint2Tex_WIDTH, gEffFireFootprint2Tex_HEIGHT, 8)];
#define gEffFireFootprint3Tex_WIDTH 32
#define gEffFireFootprint3Tex_HEIGHT 32
extern u64 gEffFireFootprint3Tex[TEX_LEN(u64, gEffFireFootprint3Tex_WIDTH, gEffFireFootprint3Tex_HEIGHT, 8)];
#define gEffFireFootprint4Tex_WIDTH 32
#define gEffFireFootprint4Tex_HEIGHT 32
extern u64 gEffFireFootprint4Tex[TEX_LEN(u64, gEffFireFootprint4Tex_WIDTH, gEffFireFootprint4Tex_HEIGHT, 8)];
#define gEffFireFootprint5Tex_WIDTH 32
#define gEffFireFootprint5Tex_HEIGHT 32
extern u64 gEffFireFootprint5Tex[TEX_LEN(u64, gEffFireFootprint5Tex_WIDTH, gEffFireFootprint5Tex_HEIGHT, 8)];
#define gEffFireFootprint6Tex_WIDTH 32
#define gEffFireFootprint6Tex_HEIGHT 32
extern u64 gEffFireFootprint6Tex[TEX_LEN(u64, gEffFireFootprint6Tex_WIDTH, gEffFireFootprint6Tex_HEIGHT, 8)];
#define gEffFireFootprint7Tex_WIDTH 32
#define gEffFireFootprint7Tex_HEIGHT 32
extern u64 gEffFireFootprint7Tex[TEX_LEN(u64, gEffFireFootprint7Tex_WIDTH, gEffFireFootprint7Tex_HEIGHT, 8)];
#define gEffFireFootprint8Tex_WIDTH 32
#define gEffFireFootprint8Tex_HEIGHT 32
extern u64 gEffFireFootprint8Tex[TEX_LEN(u64, gEffFireFootprint8Tex_WIDTH, gEffFireFootprint8Tex_HEIGHT, 8)];
extern Gfx gEffFireFootprintDL[12];
extern Vtx gEffFireFootprintVtx[];
#define gEffUnusedBubbles1Tex_WIDTH 32
#define gEffUnusedBubbles1Tex_HEIGHT 32
extern u64 gEffUnusedBubbles1Tex[TEX_LEN(u64, gEffUnusedBubbles1Tex_WIDTH, gEffUnusedBubbles1Tex_HEIGHT, 8)];
#define gEffUnusedBubbles2Tex_WIDTH 32
#define gEffUnusedBubbles2Tex_HEIGHT 32
extern u64 gEffUnusedBubbles2Tex[TEX_LEN(u64, gEffUnusedBubbles2Tex_WIDTH, gEffUnusedBubbles2Tex_HEIGHT, 8)];
#define gEffUnusedBubbles3Tex_WIDTH 32
#define gEffUnusedBubbles3Tex_HEIGHT 32
extern u64 gEffUnusedBubbles3Tex[TEX_LEN(u64, gEffUnusedBubbles3Tex_WIDTH, gEffUnusedBubbles3Tex_HEIGHT, 8)];
#define gEffUnusedBubbles4Tex_WIDTH 32
#define gEffUnusedBubbles4Tex_HEIGHT 32
extern u64 gEffUnusedBubbles4Tex[TEX_LEN(u64, gEffUnusedBubbles4Tex_WIDTH, gEffUnusedBubbles4Tex_HEIGHT, 8)];
#define gEffUnusedBubbles5Tex_WIDTH 32
#define gEffUnusedBubbles5Tex_HEIGHT 32
extern u64 gEffUnusedBubbles5Tex[TEX_LEN(u64, gEffUnusedBubbles5Tex_WIDTH, gEffUnusedBubbles5Tex_HEIGHT, 8)];
#define gEffUnusedBubbles6Tex_WIDTH 32
#define gEffUnusedBubbles6Tex_HEIGHT 32
extern u64 gEffUnusedBubbles6Tex[TEX_LEN(u64, gEffUnusedBubbles6Tex_WIDTH, gEffUnusedBubbles6Tex_HEIGHT, 8)];
#define gEffUnusedBubbles7Tex_WIDTH 32
#define gEffUnusedBubbles7Tex_HEIGHT 32
extern u64 gEffUnusedBubbles7Tex[TEX_LEN(u64, gEffUnusedBubbles7Tex_WIDTH, gEffUnusedBubbles7Tex_HEIGHT, 8)];
#define gEffUnusedBubbles8Tex_WIDTH 32
#define gEffUnusedBubbles8Tex_HEIGHT 32
extern u64 gEffUnusedBubbles8Tex[TEX_LEN(u64, gEffUnusedBubbles8Tex_WIDTH, gEffUnusedBubbles8Tex_HEIGHT, 8)];
extern Gfx gEffUnusedBubblesDL[14];
extern Vtx gEffUnusedBubblesVtx[];
#define gLensOfTruthMaskTex_WIDTH 64
#define gLensOfTruthMaskTex_HEIGHT 64
extern u64 gLensOfTruthMaskTex[TEX_LEN(u64, gLensOfTruthMaskTex_WIDTH, gLensOfTruthMaskTex_HEIGHT, 8)];
#define gEffHitMark1Tex_WIDTH 32
#define gEffHitMark1Tex_HEIGHT 24
extern u64 gEffHitMark1Tex[TEX_LEN(u64, gEffHitMark1Tex_WIDTH, gEffHitMark1Tex_HEIGHT, 4)];
#define gEffHitMark2Tex_WIDTH 32
#define gEffHitMark2Tex_HEIGHT 24
extern u64 gEffHitMark2Tex[TEX_LEN(u64, gEffHitMark2Tex_WIDTH, gEffHitMark2Tex_HEIGHT, 4)];
#define gEffHitMark3Tex_WIDTH 32
#define gEffHitMark3Tex_HEIGHT 24
extern u64 gEffHitMark3Tex[TEX_LEN(u64, gEffHitMark3Tex_WIDTH, gEffHitMark3Tex_HEIGHT, 4)];
#define gEffHitMark4Tex_WIDTH 32
#define gEffHitMark4Tex_HEIGHT 24
extern u64 gEffHitMark4Tex[TEX_LEN(u64, gEffHitMark4Tex_WIDTH, gEffHitMark4Tex_HEIGHT, 4)];
#define gEffHitMark5Tex_WIDTH 32
#define gEffHitMark5Tex_HEIGHT 24
extern u64 gEffHitMark5Tex[TEX_LEN(u64, gEffHitMark5Tex_WIDTH, gEffHitMark5Tex_HEIGHT, 4)];
#define gEffHitMark6Tex_WIDTH 32
#define gEffHitMark6Tex_HEIGHT 24
extern u64 gEffHitMark6Tex[TEX_LEN(u64, gEffHitMark6Tex_WIDTH, gEffHitMark6Tex_HEIGHT, 4)];
#define gEffHitMark7Tex_WIDTH 32
#define gEffHitMark7Tex_HEIGHT 24
extern u64 gEffHitMark7Tex[TEX_LEN(u64, gEffHitMark7Tex_WIDTH, gEffHitMark7Tex_HEIGHT, 4)];
#define gEffHitMark8Tex_WIDTH 32
#define gEffHitMark8Tex_HEIGHT 24
extern u64 gEffHitMark8Tex[TEX_LEN(u64, gEffHitMark8Tex_WIDTH, gEffHitMark8Tex_HEIGHT, 4)];
#define gEffHitMark9Tex_WIDTH 32
#define gEffHitMark9Tex_HEIGHT 24
extern u64 gEffHitMark9Tex[TEX_LEN(u64, gEffHitMark9Tex_WIDTH, gEffHitMark9Tex_HEIGHT, 4)];
#define gEffHitMark10Tex_WIDTH 32
#define gEffHitMark10Tex_HEIGHT 24
extern u64 gEffHitMark10Tex[TEX_LEN(u64, gEffHitMark10Tex_WIDTH, gEffHitMark10Tex_HEIGHT, 4)];
#define gEffHitMark11Tex_WIDTH 32
#define gEffHitMark11Tex_HEIGHT 24
extern u64 gEffHitMark11Tex[TEX_LEN(u64, gEffHitMark11Tex_WIDTH, gEffHitMark11Tex_HEIGHT, 4)];
#define gEffHitMark12Tex_WIDTH 32
#define gEffHitMark12Tex_HEIGHT 24
extern u64 gEffHitMark12Tex[TEX_LEN(u64, gEffHitMark12Tex_WIDTH, gEffHitMark12Tex_HEIGHT, 4)];
#define gEffHitMark13Tex_WIDTH 32
#define gEffHitMark13Tex_HEIGHT 24
extern u64 gEffHitMark13Tex[TEX_LEN(u64, gEffHitMark13Tex_WIDTH, gEffHitMark13Tex_HEIGHT, 4)];
#define gEffHitMark14Tex_WIDTH 32
#define gEffHitMark14Tex_HEIGHT 24
extern u64 gEffHitMark14Tex[TEX_LEN(u64, gEffHitMark14Tex_WIDTH, gEffHitMark14Tex_HEIGHT, 4)];
#define gEffHitMark15Tex_WIDTH 32
#define gEffHitMark15Tex_HEIGHT 24
extern u64 gEffHitMark15Tex[TEX_LEN(u64, gEffHitMark15Tex_WIDTH, gEffHitMark15Tex_HEIGHT, 4)];
#define gEffHitMark16Tex_WIDTH 32
#define gEffHitMark16Tex_HEIGHT 24
extern u64 gEffHitMark16Tex[TEX_LEN(u64, gEffHitMark16Tex_WIDTH, gEffHitMark16Tex_HEIGHT, 4)];
#define gEffHitMark17Tex_WIDTH 32
#define gEffHitMark17Tex_HEIGHT 24
extern u64 gEffHitMark17Tex[TEX_LEN(u64, gEffHitMark17Tex_WIDTH, gEffHitMark17Tex_HEIGHT, 4)];
#define gEffHitMark18Tex_WIDTH 32
#define gEffHitMark18Tex_HEIGHT 24
extern u64 gEffHitMark18Tex[TEX_LEN(u64, gEffHitMark18Tex_WIDTH, gEffHitMark18Tex_HEIGHT, 4)];
#define gEffHitMark19Tex_WIDTH 32
#define gEffHitMark19Tex_HEIGHT 24
extern u64 gEffHitMark19Tex[TEX_LEN(u64, gEffHitMark19Tex_WIDTH, gEffHitMark19Tex_HEIGHT, 4)];
#define gEffHitMark20Tex_WIDTH 32
#define gEffHitMark20Tex_HEIGHT 24
extern u64 gEffHitMark20Tex[TEX_LEN(u64, gEffHitMark20Tex_WIDTH, gEffHitMark20Tex_HEIGHT, 4)];
#define gEffHitMark21Tex_WIDTH 32
#define gEffHitMark21Tex_HEIGHT 24
extern u64 gEffHitMark21Tex[TEX_LEN(u64, gEffHitMark21Tex_WIDTH, gEffHitMark21Tex_HEIGHT, 4)];
#define gEffHitMark22Tex_WIDTH 32
#define gEffHitMark22Tex_HEIGHT 24
extern u64 gEffHitMark22Tex[TEX_LEN(u64, gEffHitMark22Tex_WIDTH, gEffHitMark22Tex_HEIGHT, 4)];
#define gEffHitMark23Tex_WIDTH 32
#define gEffHitMark23Tex_HEIGHT 24
extern u64 gEffHitMark23Tex[TEX_LEN(u64, gEffHitMark23Tex_WIDTH, gEffHitMark23Tex_HEIGHT, 4)];
#define gEffHitMark24Tex_WIDTH 32
#define gEffHitMark24Tex_HEIGHT 24
extern u64 gEffHitMark24Tex[TEX_LEN(u64, gEffHitMark24Tex_WIDTH, gEffHitMark24Tex_HEIGHT, 4)];
extern Gfx gEffHitMarkDL[11];
extern Vtx gEffHitMarkVtx[];
#define gEffUnknown6Tex_WIDTH 32
#define gEffUnknown6Tex_HEIGHT 64
extern u64 gEffUnknown6Tex[TEX_LEN(u64, gEffUnknown6Tex_WIDTH, gEffUnknown6Tex_HEIGHT, 8)];
#define gEffFleckTex_WIDTH 64
#define gEffFleckTex_HEIGHT 64
extern u64 gEffFleckTex[TEX_LEN(u64, gEffFleckTex_WIDTH, gEffFleckTex_HEIGHT, 4)];
#define gEffUnknown8Tex_WIDTH 64
#define gEffUnknown8Tex_HEIGHT 64
extern u64 gEffUnknown8Tex[TEX_LEN(u64, gEffUnknown8Tex_WIDTH, gEffUnknown8Tex_HEIGHT, 8)];
#define gEffMagmaBubble1Tex_WIDTH 16
#define gEffMagmaBubble1Tex_HEIGHT 24
extern u64 gEffMagmaBubble1Tex[TEX_LEN(u64, gEffMagmaBubble1Tex_WIDTH, gEffMagmaBubble1Tex_HEIGHT, 8)];
#define gEffMagmaBubble2Tex_WIDTH 16
#define gEffMagmaBubble2Tex_HEIGHT 24
extern u64 gEffMagmaBubble2Tex[TEX_LEN(u64, gEffMagmaBubble2Tex_WIDTH, gEffMagmaBubble2Tex_HEIGHT, 8)];
#define gEffMagmaBubble3Tex_WIDTH 16
#define gEffMagmaBubble3Tex_HEIGHT 24
extern u64 gEffMagmaBubble3Tex[TEX_LEN(u64, gEffMagmaBubble3Tex_WIDTH, gEffMagmaBubble3Tex_HEIGHT, 8)];
#define gEffMagmaBubble4Tex_WIDTH 16
#define gEffMagmaBubble4Tex_HEIGHT 24
extern u64 gEffMagmaBubble4Tex[TEX_LEN(u64, gEffMagmaBubble4Tex_WIDTH, gEffMagmaBubble4Tex_HEIGHT, 8)];
#define gEffMagmaBubble5Tex_WIDTH 16
#define gEffMagmaBubble5Tex_HEIGHT 24
extern u64 gEffMagmaBubble5Tex[TEX_LEN(u64, gEffMagmaBubble5Tex_WIDTH, gEffMagmaBubble5Tex_HEIGHT, 8)];
#define gEffMagmaBubble6Tex_WIDTH 16
#define gEffMagmaBubble6Tex_HEIGHT 24
extern u64 gEffMagmaBubble6Tex[TEX_LEN(u64, gEffMagmaBubble6Tex_WIDTH, gEffMagmaBubble6Tex_HEIGHT, 8)];
#define gEffMagmaBubble7Tex_WIDTH 16
#define gEffMagmaBubble7Tex_HEIGHT 24
extern u64 gEffMagmaBubble7Tex[TEX_LEN(u64, gEffMagmaBubble7Tex_WIDTH, gEffMagmaBubble7Tex_HEIGHT, 8)];
#define gEffMagmaBubble8Tex_WIDTH 16
#define gEffMagmaBubble8Tex_HEIGHT 24
extern u64 gEffMagmaBubble8Tex[TEX_LEN(u64, gEffMagmaBubble8Tex_WIDTH, gEffMagmaBubble8Tex_HEIGHT, 8)];
extern Gfx gEffMagmaBubbleDL[12];
extern Vtx gEffMagmaBubbleVtx[];
#define gEffWaterRippleTex_WIDTH 64
#define gEffWaterRippleTex_HEIGHT 64
extern u64 gEffWaterRippleTex[TEX_LEN(u64, gEffWaterRippleTex_WIDTH, gEffWaterRippleTex_HEIGHT, 8)];
extern Gfx gEffWaterRippleDL[12];
extern Vtx gEffWaterRippleVtx[];
extern Gfx gEffSparkDL[12];
extern Vtx gEffSparkVtx[];
#define gEffWaterSplash1Tex_WIDTH 32
#define gEffWaterSplash1Tex_HEIGHT 40
extern u64 gEffWaterSplash1Tex[TEX_LEN(u64, gEffWaterSplash1Tex_WIDTH, gEffWaterSplash1Tex_HEIGHT, 8)];
#define gEffWaterSplash2Tex_WIDTH 32
#define gEffWaterSplash2Tex_HEIGHT 40
extern u64 gEffWaterSplash2Tex[TEX_LEN(u64, gEffWaterSplash2Tex_WIDTH, gEffWaterSplash2Tex_HEIGHT, 8)];
#define gEffWaterSplash3Tex_WIDTH 32
#define gEffWaterSplash3Tex_HEIGHT 40
extern u64 gEffWaterSplash3Tex[TEX_LEN(u64, gEffWaterSplash3Tex_WIDTH, gEffWaterSplash3Tex_HEIGHT, 8)];
#define gEffWaterSplash4Tex_WIDTH 32
#define gEffWaterSplash4Tex_HEIGHT 40
extern u64 gEffWaterSplash4Tex[TEX_LEN(u64, gEffWaterSplash4Tex_WIDTH, gEffWaterSplash4Tex_HEIGHT, 8)];
#define gEffWaterSplash5Tex_WIDTH 32
#define gEffWaterSplash5Tex_HEIGHT 40
extern u64 gEffWaterSplash5Tex[TEX_LEN(u64, gEffWaterSplash5Tex_WIDTH, gEffWaterSplash5Tex_HEIGHT, 8)];
#define gEffWaterSplash6Tex_WIDTH 32
#define gEffWaterSplash6Tex_HEIGHT 40
extern u64 gEffWaterSplash6Tex[TEX_LEN(u64, gEffWaterSplash6Tex_WIDTH, gEffWaterSplash6Tex_HEIGHT, 8)];
#define gEffWaterSplash7Tex_WIDTH 32
#define gEffWaterSplash7Tex_HEIGHT 40
extern u64 gEffWaterSplash7Tex[TEX_LEN(u64, gEffWaterSplash7Tex_WIDTH, gEffWaterSplash7Tex_HEIGHT, 8)];
#define gEffWaterSplash8Tex_WIDTH 32
#define gEffWaterSplash8Tex_HEIGHT 40
extern u64 gEffWaterSplash8Tex[TEX_LEN(u64, gEffWaterSplash8Tex_WIDTH, gEffWaterSplash8Tex_HEIGHT, 8)];
extern Gfx gEffWaterSplashDL[12];
extern Vtx gEffWaterSplashVtx[];
#define gUnknownEffStone1Tex_WIDTH 32
#define gUnknownEffStone1Tex_HEIGHT 32
extern u64 gUnknownEffStone1Tex[TEX_LEN(u64, gUnknownEffStone1Tex_WIDTH, gUnknownEffStone1Tex_HEIGHT, 8)];
#define gUnknownEffStone2Tex_WIDTH 32
#define gUnknownEffStone2Tex_HEIGHT 32
extern u64 gUnknownEffStone2Tex[TEX_LEN(u64, gUnknownEffStone2Tex_WIDTH, gUnknownEffStone2Tex_HEIGHT, 8)];
#define gUnknownEffStone3Tex_WIDTH 32
#define gUnknownEffStone3Tex_HEIGHT 32
extern u64 gUnknownEffStone3Tex[TEX_LEN(u64, gUnknownEffStone3Tex_WIDTH, gUnknownEffStone3Tex_HEIGHT, 8)];
#define gUnknownEffStone4Tex_WIDTH 32
#define gUnknownEffStone4Tex_HEIGHT 32
extern u64 gUnknownEffStone4Tex[TEX_LEN(u64, gUnknownEffStone4Tex_WIDTH, gUnknownEffStone4Tex_HEIGHT, 8)];
#define gUnknownEffStone5Tex_WIDTH 32
#define gUnknownEffStone5Tex_HEIGHT 32
extern u64 gUnknownEffStone5Tex[TEX_LEN(u64, gUnknownEffStone5Tex_WIDTH, gUnknownEffStone5Tex_HEIGHT, 8)];
#define gUnknownEffStone6Tex_WIDTH 32
#define gUnknownEffStone6Tex_HEIGHT 32
extern u64 gUnknownEffStone6Tex[TEX_LEN(u64, gUnknownEffStone6Tex_WIDTH, gUnknownEffStone6Tex_HEIGHT, 8)];
#define gUnknownEffStone7Tex_WIDTH 32
#define gUnknownEffStone7Tex_HEIGHT 32
extern u64 gUnknownEffStone7Tex[TEX_LEN(u64, gUnknownEffStone7Tex_WIDTH, gUnknownEffStone7Tex_HEIGHT, 8)];
#define gUnknownEffStone8Tex_WIDTH 32
#define gUnknownEffStone8Tex_HEIGHT 32
extern u64 gUnknownEffStone8Tex[TEX_LEN(u64, gUnknownEffStone8Tex_WIDTH, gUnknownEffStone8Tex_HEIGHT, 8)];
extern Gfx gUnknownEffStoneDL[12];
extern Vtx gUnknownEffStoneVtx[];
#define gEffLightning1Tex_WIDTH 16
#define gEffLightning1Tex_HEIGHT 96
extern u64 gEffLightning1Tex[TEX_LEN(u64, gEffLightning1Tex_WIDTH, gEffLightning1Tex_HEIGHT, 8)];
#define gEffLightning2Tex_WIDTH 16
#define gEffLightning2Tex_HEIGHT 96
extern u64 gEffLightning2Tex[TEX_LEN(u64, gEffLightning2Tex_WIDTH, gEffLightning2Tex_HEIGHT, 8)];
#define gEffLightning3Tex_WIDTH 16
#define gEffLightning3Tex_HEIGHT 96
extern u64 gEffLightning3Tex[TEX_LEN(u64, gEffLightning3Tex_WIDTH, gEffLightning3Tex_HEIGHT, 8)];
#define gEffLightning4Tex_WIDTH 16
#define gEffLightning4Tex_HEIGHT 96
extern u64 gEffLightning4Tex[TEX_LEN(u64, gEffLightning4Tex_WIDTH, gEffLightning4Tex_HEIGHT, 8)];
#define gEffLightning5Tex_WIDTH 16
#define gEffLightning5Tex_HEIGHT 96
extern u64 gEffLightning5Tex[TEX_LEN(u64, gEffLightning5Tex_WIDTH, gEffLightning5Tex_HEIGHT, 8)];
#define gEffLightning6Tex_WIDTH 16
#define gEffLightning6Tex_HEIGHT 96
extern u64 gEffLightning6Tex[TEX_LEN(u64, gEffLightning6Tex_WIDTH, gEffLightning6Tex_HEIGHT, 8)];
#define gEffLightning7Tex_WIDTH 16
#define gEffLightning7Tex_HEIGHT 96
extern u64 gEffLightning7Tex[TEX_LEN(u64, gEffLightning7Tex_WIDTH, gEffLightning7Tex_HEIGHT, 8)];
#define gEffLightning8Tex_WIDTH 16
#define gEffLightning8Tex_HEIGHT 96
extern u64 gEffLightning8Tex[TEX_LEN(u64, gEffLightning8Tex_WIDTH, gEffLightning8Tex_HEIGHT, 8)];
extern Gfx gEffLightningDL[13];
extern Vtx gEffLightningVtx[];
#define gEffEnemyDeathFlame1Tex_WIDTH 32
#define gEffEnemyDeathFlame1Tex_HEIGHT 64
extern u64 gEffEnemyDeathFlame1Tex[TEX_LEN(u64, gEffEnemyDeathFlame1Tex_WIDTH, gEffEnemyDeathFlame1Tex_HEIGHT, 8)];
#define gEffEnemyDeathFlame2Tex_WIDTH 32
#define gEffEnemyDeathFlame2Tex_HEIGHT 64
extern u64 gEffEnemyDeathFlame2Tex[TEX_LEN(u64, gEffEnemyDeathFlame2Tex_WIDTH, gEffEnemyDeathFlame2Tex_HEIGHT, 8)];
#define gEffEnemyDeathFlame3Tex_WIDTH 32
#define gEffEnemyDeathFlame3Tex_HEIGHT 64
extern u64 gEffEnemyDeathFlame3Tex[TEX_LEN(u64, gEffEnemyDeathFlame3Tex_WIDTH, gEffEnemyDeathFlame3Tex_HEIGHT, 8)];
#define gEffEnemyDeathFlame4Tex_WIDTH 32
#define gEffEnemyDeathFlame4Tex_HEIGHT 64
extern u64 gEffEnemyDeathFlame4Tex[TEX_LEN(u64, gEffEnemyDeathFlame4Tex_WIDTH, gEffEnemyDeathFlame4Tex_HEIGHT, 8)];
#define gEffEnemyDeathFlame5Tex_WIDTH 32
#define gEffEnemyDeathFlame5Tex_HEIGHT 64
extern u64 gEffEnemyDeathFlame5Tex[TEX_LEN(u64, gEffEnemyDeathFlame5Tex_WIDTH, gEffEnemyDeathFlame5Tex_HEIGHT, 8)];
#define gEffEnemyDeathFlame6Tex_WIDTH 32
#define gEffEnemyDeathFlame6Tex_HEIGHT 64
extern u64 gEffEnemyDeathFlame6Tex[TEX_LEN(u64, gEffEnemyDeathFlame6Tex_WIDTH, gEffEnemyDeathFlame6Tex_HEIGHT, 8)];
#define gEffEnemyDeathFlame7Tex_WIDTH 32
#define gEffEnemyDeathFlame7Tex_HEIGHT 64
extern u64 gEffEnemyDeathFlame7Tex[TEX_LEN(u64, gEffEnemyDeathFlame7Tex_WIDTH, gEffEnemyDeathFlame7Tex_HEIGHT, 8)];
#define gEffEnemyDeathFlame8Tex_WIDTH 32
#define gEffEnemyDeathFlame8Tex_HEIGHT 64
extern u64 gEffEnemyDeathFlame8Tex[TEX_LEN(u64, gEffEnemyDeathFlame8Tex_WIDTH, gEffEnemyDeathFlame8Tex_HEIGHT, 8)];
#define gEffEnemyDeathFlame9Tex_WIDTH 32
#define gEffEnemyDeathFlame9Tex_HEIGHT 64
extern u64 gEffEnemyDeathFlame9Tex[TEX_LEN(u64, gEffEnemyDeathFlame9Tex_WIDTH, gEffEnemyDeathFlame9Tex_HEIGHT, 8)];
#define gEffEnemyDeathFlame10Tex_WIDTH 32
#define gEffEnemyDeathFlame10Tex_HEIGHT 64
extern u64 gEffEnemyDeathFlame10Tex[TEX_LEN(u64, gEffEnemyDeathFlame10Tex_WIDTH, gEffEnemyDeathFlame10Tex_HEIGHT, 8)];
extern Gfx gEffEnemyDeathFlameDL[13];
extern Vtx gEffEnemyDeathFlameVtx[];
#define gEffUnknown9Tex_WIDTH 32
#define gEffUnknown9Tex_HEIGHT 32
extern u64 gEffUnknown9Tex[TEX_LEN(u64, gEffUnknown9Tex_WIDTH, gEffUnknown9Tex_HEIGHT, 8)];
#define gEffUnknown10Tex_WIDTH 32
#define gEffUnknown10Tex_HEIGHT 32
extern u64 gEffUnknown10Tex[TEX_LEN(u64, gEffUnknown10Tex_WIDTH, gEffUnknown10Tex_HEIGHT, 8)];
#define gEffUnknown11Tex_WIDTH 32
#define gEffUnknown11Tex_HEIGHT 32
extern u64 gEffUnknown11Tex[TEX_LEN(u64, gEffUnknown11Tex_WIDTH, gEffUnknown11Tex_HEIGHT, 8)];
#define gEffUnknown12Tex_WIDTH 32
#define gEffUnknown12Tex_HEIGHT 32
extern u64 gEffUnknown12Tex[TEX_LEN(u64, gEffUnknown12Tex_WIDTH, gEffUnknown12Tex_HEIGHT, 8)];
#define gUnknownWoodBoardTex_WIDTH 32
#define gUnknownWoodBoardTex_HEIGHT 32
extern u64 gUnknownWoodBoardTex[TEX_LEN(u64, gUnknownWoodBoardTex_WIDTH, gUnknownWoodBoardTex_HEIGHT, 8)];
extern Vtx gEffIceFragmentVtx[];
extern Gfx gEffIceFragment1DL[31];
extern Gfx gEffIceFragment2DL[30];
extern Vtx gEffIceFragment3Vtx[];
extern Gfx gEffIceFragment3DL[46];
extern s16 gBugCrawlFrameData[];
extern JointIndex gBugCrawlJointIndices[];
extern AnimationHeader gBugCrawlAnim;
extern Gfx gBugLimb1DL[20];
extern Gfx gBugLimb1WrapperDL[2];
extern Gfx gBugLimb1WrapperWrapperDL[2];
extern Vtx gBugLimb1Vtx[];
extern Gfx gBugLimb2DL[20];
extern Gfx gBugLimb2WrapperDL[2];
extern Gfx gBugLimb2WrapperWrapperDL[2];
extern Vtx gBugLimb2Vtx[];
extern Gfx gBugLimb3DL[20];
extern Gfx gBugLimb3WrapperDL[2];
extern Gfx gBugLimb3WrapperWrapperDL[2];
extern Vtx gBugLimb3Vtx[];
extern Gfx gBugLimb4DL[20];
extern Gfx gBugLimb4WrapperDL[2];
extern Gfx gBugLimb4WrapperWrapperDL[2];
extern Vtx gBugLimb4Vtx[];
extern Gfx gBugLimb5DL[20];
extern Gfx gBugLimb5WrapperDL[2];
extern Gfx gBugLimb5WrapperWrapperDL[2];
extern Vtx gBugLimb5Vtx[];
extern Gfx gBugLimb6DL[20];
extern Gfx gBugLimb6WrapperDL[2];
extern Gfx gBugLimb6WrapperWrapperDL[2];
extern Vtx gBugLimb6Vtx[];
extern Gfx gBugLimb7DL[20];
extern Gfx gBugLimb7WrapperDL[2];
extern Gfx gBugLimb7WrapperWrapperDL[2];
extern Vtx gBugLimb7Vtx[];
extern Gfx gBugLimb8DL[20];
extern Gfx gBugLimb8WrapperDL[2];
extern Gfx gBugLimb8WrapperWrapperDL[2];
extern Vtx gBugLimb8Vtx[];
extern Gfx gBugLimb9DL[22];
extern Gfx gBugLimb9WrapperDL[2];
extern Gfx gBugLimb9WrapperWrapperDL[2];
extern Vtx gBugLimb9Vtx[];
#define gBugBodyTex_WIDTH 16
#define gBugBodyTex_HEIGHT 64
extern u64 gBugBodyTex[TEX_LEN(u64, gBugBodyTex_WIDTH, gBugBodyTex_HEIGHT, 16)];
#define gBugLegTex_WIDTH 8
#define gBugLegTex_HEIGHT 16
extern u64 gBugLegTex[TEX_LEN(u64, gBugLegTex_WIDTH, gBugLegTex_HEIGHT, 16)];
extern StandardLimb gameplay_keep_0358C0_Limb;
extern StandardLimb gameplay_keep_0358CC_Limb;
extern StandardLimb gameplay_keep_0358D8_Limb;
extern StandardLimb gameplay_keep_0358E4_Limb;
extern StandardLimb gameplay_keep_0358F0_Limb;
extern StandardLimb gameplay_keep_0358FC_Limb;
extern StandardLimb gameplay_keep_035908_Limb;
extern StandardLimb gameplay_keep_035914_Limb;
extern StandardLimb gameplay_keep_035920_Limb;
extern StandardLimb gameplay_keep_03592C_Limb;
extern StandardLimb gameplay_keep_035938_Limb;
extern StandardLimb gameplay_keep_035944_Limb;
extern StandardLimb gameplay_keep_035950_Limb;
extern StandardLimb gameplay_keep_03595C_Limb;
extern StandardLimb gameplay_keep_035968_Limb;
extern StandardLimb gameplay_keep_035974_Limb;
extern StandardLimb gameplay_keep_035980_Limb;
extern StandardLimb gameplay_keep_03598C_Limb;
extern StandardLimb gameplay_keep_035998_Limb;
extern StandardLimb gameplay_keep_0359A4_Limb;
extern StandardLimb gameplay_keep_0359B0_Limb;
extern StandardLimb gameplay_keep_0359BC_Limb;
extern StandardLimb gameplay_keep_0359C8_Limb;
extern void* gBugLimbs[];
typedef enum gBugSkelLimb {
    /*  0 */ LIMB_GAMEPLAY_KEEP_035A30_NONE,
    /*  1 */ LIMB_GAMEPLAY_KEEP_0358C0,
    /*  2 */ LIMB_GAMEPLAY_KEEP_0358CC,
    /*  3 */ LIMB_GAMEPLAY_KEEP_0358D8,
    /*  4 */ LIMB_GAMEPLAY_KEEP_0358E4,
    /*  5 */ LIMB_GAMEPLAY_KEEP_0358F0,
    /*  6 */ LIMB_GAMEPLAY_KEEP_0358FC,
    /*  7 */ LIMB_GAMEPLAY_KEEP_035908,
    /*  8 */ LIMB_GAMEPLAY_KEEP_035914,
    /*  9 */ LIMB_GAMEPLAY_KEEP_035920,
    /* 10 */ LIMB_GAMEPLAY_KEEP_03592C,
    /* 11 */ LIMB_GAMEPLAY_KEEP_035938,
    /* 12 */ LIMB_GAMEPLAY_KEEP_035944,
    /* 13 */ LIMB_GAMEPLAY_KEEP_035950,
    /* 14 */ LIMB_GAMEPLAY_KEEP_03595C,
    /* 15 */ LIMB_GAMEPLAY_KEEP_035968,
    /* 16 */ LIMB_GAMEPLAY_KEEP_035974,
    /* 17 */ LIMB_GAMEPLAY_KEEP_035980,
    /* 18 */ LIMB_GAMEPLAY_KEEP_03598C,
    /* 19 */ LIMB_GAMEPLAY_KEEP_035998,
    /* 20 */ LIMB_GAMEPLAY_KEEP_0359A4,
    /* 21 */ LIMB_GAMEPLAY_KEEP_0359B0,
    /* 22 */ LIMB_GAMEPLAY_KEEP_0359BC,
    /* 23 */ LIMB_GAMEPLAY_KEEP_0359C8,
    /* 24 */ LIMB_GAMEPLAY_KEEP_035A30_MAX
} gBugSkelLimb;
extern SkeletonHeader gBugSkel;
extern Vtx gCuttableShrubStalkVtx[];
extern Gfx gCuttableShrubStalkDL[18];
extern Vtx gCuttableShrubTipVtx[];
extern Gfx gCuttableShrubTipDL[18];
#define gCuttableShrubLeafTFragmentTex_WIDTH 32
#define gCuttableShrubLeafTFragmentTex_HEIGHT 32
extern u64 gCuttableShrubLeafTFragmentTex[TEX_LEN(u64, gCuttableShrubLeafTFragmentTex_WIDTH, gCuttableShrubLeafTFragmentTex_HEIGHT, 16)];
#define gCuttableShrubTex_WIDTH 32
#define gCuttableShrubTex_HEIGHT 32
extern u64 gCuttableShrubTex[TEX_LEN(u64, gCuttableShrubTex_WIDTH, gCuttableShrubTex_HEIGHT, 16)];
#define gLensFlareCircleTex_WIDTH 64
#define gLensFlareCircleTex_HEIGHT 64
extern u64 gLensFlareCircleTex[TEX_LEN(u64, gLensFlareCircleTex_WIDTH, gLensFlareCircleTex_HEIGHT, 4)];
#define gLensFlareRingTex_WIDTH 64
#define gLensFlareRingTex_HEIGHT 64
extern u64 gLensFlareRingTex[TEX_LEN(u64, gLensFlareRingTex_WIDTH, gLensFlareRingTex_HEIGHT, 4)];
extern Gfx gLensFlareCircleDL[13];
extern Gfx gLensFlareRingDL[13];
extern Vtx gLensFlareVtx[];
extern Vtx gEffSparklesVtx[];
extern Gfx gEffSparklesDL[12];
#define gEffSparklesTex_WIDTH 16
#define gEffSparklesTex_HEIGHT 16
extern u64 gEffSparklesTex[TEX_LEN(u64, gEffSparklesTex_WIDTH, gEffSparklesTex_HEIGHT, 4)];
#define gEffUnknown13Tex_WIDTH 16
#define gEffUnknown13Tex_HEIGHT 32
extern u64 gEffUnknown13Tex[TEX_LEN(u64, gEffUnknown13Tex_WIDTH, gEffUnknown13Tex_HEIGHT, 8)];
#define gEffUnknown14Tex_WIDTH 16
#define gEffUnknown14Tex_HEIGHT 32
extern u64 gEffUnknown14Tex[TEX_LEN(u64, gEffUnknown14Tex_WIDTH, gEffUnknown14Tex_HEIGHT, 8)];
extern Vtx gHoverBootsCircleVtx[];
extern Gfx gHoverBootsCircleDL[26];
#define gMoonTex_WIDTH 64
#define gMoonTex_HEIGHT 64
extern u64 gMoonTex[TEX_LEN(u64, gMoonTex_WIDTH, gMoonTex_HEIGHT, 8)];
extern Gfx gMoonDL[14];
extern Vtx gMoonVtx[];
#define gUnknownCircle6Tex_WIDTH 32
#define gUnknownCircle6Tex_HEIGHT 32
extern u64 gUnknownCircle6Tex[TEX_LEN(u64, gUnknownCircle6Tex_WIDTH, gUnknownCircle6Tex_HEIGHT, 8)];
extern Vtx gameplay_keep_Vtx_039850[];
extern Gfx gGameplayKeepDL_39890[27];
extern Vtx gameplay_keep_Vtx_039970[];
extern Gfx gGameplayKeepDL_399B0[17];
extern Vtx gameplay_keep_Vtx_039A40[];
extern Gfx gGameplayKeepDL_39A80[17];
extern Vtx gameplay_keep_Vtx_039B10[];
extern Gfx gGameplayKeepDL_39B50[17];
extern BgCamInfo gLargerCubeBgCamList[];
extern SurfaceType gLargerCubeSurfaceTypes[];
extern CollisionPoly gLargerCubePolyList[];
extern Vec3s gLargerCubeVtxList[];
extern CollisionHeader gLargerCubeCol;
extern Vtx gLiftableRockVtx[];
extern Gfx gLiftableRockDL[22];
extern Vtx gUnusedRockRectangularPrism1Vtx[];
extern Gfx gUnusedRockRectangularPrism1DL[22];
extern BgCamInfo gWideTallBlockBgCamList[];
extern SurfaceType gWideTallBlockSurfaceTypes[];
extern CollisionPoly gWideTallBlockPolyList[];
extern Vec3s gWideTallBlockVtxList[];
extern CollisionHeader gWideTallBlockCol;
extern Vtx gFlatBlockVtx[];
extern Gfx gFlatBlockDL[23];
extern BgCamInfo gTallBlockBgCamList[];
extern SurfaceType gTallBlockSurfaceTypes[];
extern CollisionPoly gTallBlockPolyList[];
extern Vec3s gTallBlockVtxList[];
extern CollisionHeader gTallBlockCol;
extern Vtx gUnusedRockRectangularPrism3Vtx[];
extern Gfx gUnusedRockRectangularPrism3DL[22];
extern BgCamInfo gSmallerFlatBlockBgCamList[];
extern SurfaceType gSmallerFlatBlockSurfaceTypes[];
extern CollisionPoly gSmallerFlatBlockPolyList[];
extern Vec3s gSmallerFlatBlockVtxList[];
extern CollisionHeader gSmallerFlatBlockCol;
extern Vtx gFlatRotBlockVtx[];
extern Gfx gFlatRotBlockDL[22];
extern BgCamInfo gLargerFlatBlockBgCamList[];
extern SurfaceType gLargerFlatBlockSurfaceTypes[];
extern CollisionPoly gLargerFlatBlockPolyList[];
extern Vec3s gLargerFlatBlockVtxList[];
extern CollisionHeader gLargerFlatBlockCol;
extern Vtx gSmallCubeVtx[];
extern Gfx gSmallCubeDL[23];
extern BgCamInfo gSmallerCubeBgCamList[];
extern SurfaceType gSmallerCubeSurfaceTypes[];
extern CollisionPoly gSmallerCubePolyList[];
extern Vec3s gSmallerCubeVtxList[];
extern CollisionHeader gSmallerCubeCol;
extern Vtx gTreeStumpVtx[];
extern Gfx gTreeStumpDL[34];
extern Vtx gGrassBladesVtx[];
extern Gfx gGrassBladesDL[21];
#define gHeartShapeTex_WIDTH 16
#define gHeartShapeTex_HEIGHT 16
extern u64 gHeartShapeTex[TEX_LEN(u64, gHeartShapeTex_WIDTH, gHeartShapeTex_HEIGHT, 8)];
extern Vtx gHeartPieceInteriorVtx[];
extern Gfx gHeartPieceInteriorDL[53];
extern Vtx gHeartPieceExteriorVtx[];
extern Vtx gHeartContainerInteriorVtx[];
extern Gfx gHeartPieceExteriorDL[39];
extern Gfx gHeartContainerInteriorDL[33];
extern Vtx gameplay_keep_Vtx_03C610[];
extern Vtx gameplay_keep_Vtx_03CB10[];
extern Gfx gGameplayKeepDL_3CFD0[39];
extern Gfx gGameplayKeepDL_3D108[34];
extern Vtx gameplay_keep_Vtx_03D220[];
extern Gfx gGameplayKeepDL_3D260[17];
extern Vtx gSignRectangularVtx[];
extern Gfx gSignRectangularDL[81];
extern Vtx gSignDirectionalVtx[];
extern Gfx gSignDirectionalDL[88];
#define gDropArrows2Tex_WIDTH 32
#define gDropArrows2Tex_HEIGHT 32
extern u64 gDropArrows2Tex[TEX_LEN(u64, gDropArrows2Tex_WIDTH, gDropArrows2Tex_HEIGHT, 16)];
#define gDropArrows1Tex_WIDTH 32
#define gDropArrows1Tex_HEIGHT 32
extern u64 gDropArrows1Tex[TEX_LEN(u64, gDropArrows1Tex_WIDTH, gDropArrows1Tex_HEIGHT, 16)];
#define gDropArrows3Tex_WIDTH 32
#define gDropArrows3Tex_HEIGHT 32
extern u64 gDropArrows3Tex[TEX_LEN(u64, gDropArrows3Tex_WIDTH, gDropArrows3Tex_HEIGHT, 16)];
#define gDropBombTex_WIDTH 32
#define gDropBombTex_HEIGHT 32
extern u64 gDropBombTex[TEX_LEN(u64, gDropBombTex_WIDTH, gDropBombTex_HEIGHT, 16)];
#define gGameplayKeepTex_3FD80_WIDTH 32
#define gGameplayKeepTex_3FD80_HEIGHT 32
extern u64 gGameplayKeepTex_3FD80[TEX_LEN(u64, gGameplayKeepTex_3FD80_WIDTH, gGameplayKeepTex_3FD80_HEIGHT, 16)];
#define gGameplayKeepTex_40580_WIDTH 32
#define gGameplayKeepTex_40580_HEIGHT 32
extern u64 gGameplayKeepTex_40580[TEX_LEN(u64, gGameplayKeepTex_40580_WIDTH, gGameplayKeepTex_40580_HEIGHT, 16)];
#define gDropRecoveryHeartTex_WIDTH 32
#define gDropRecoveryHeartTex_HEIGHT 32
extern u64 gDropRecoveryHeartTex[TEX_LEN(u64, gDropRecoveryHeartTex_WIDTH, gDropRecoveryHeartTex_HEIGHT, 16)];
#define gGameplayKeepTex_41580_WIDTH 32
#define gGameplayKeepTex_41580_HEIGHT 32
extern u64 gGameplayKeepTex_41580[TEX_LEN(u64, gGameplayKeepTex_41580_WIDTH, gGameplayKeepTex_41580_HEIGHT, 16)];
extern Gfx gItemDropDL[17];
extern Vtx gItemDropVtx[];
#define gDropKeySmallTex_WIDTH 32
#define gDropKeySmallTex_HEIGHT 32
extern u64 gDropKeySmallTex[TEX_LEN(u64, gDropKeySmallTex_WIDTH, gDropKeySmallTex_HEIGHT, 16)];
#define gDropMagicSmallTex_WIDTH 32
#define gDropMagicSmallTex_HEIGHT 32
extern u64 gDropMagicSmallTex[TEX_LEN(u64, gDropMagicSmallTex_WIDTH, gDropMagicSmallTex_HEIGHT, 16)];
#define gDropDekuNutTex_WIDTH 32
#define gDropDekuNutTex_HEIGHT 32
extern u64 gDropDekuNutTex[TEX_LEN(u64, gDropDekuNutTex_WIDTH, gDropDekuNutTex_HEIGHT, 16)];
#define gDropDekuSeedsTex_WIDTH 32
#define gDropDekuSeedsTex_HEIGHT 32
extern u64 gDropDekuSeedsTex[TEX_LEN(u64, gDropDekuSeedsTex_WIDTH, gDropDekuSeedsTex_HEIGHT, 16)];
#define gDropDekuStickTex_WIDTH 32
#define gDropDekuStickTex_HEIGHT 32
extern u64 gDropDekuStickTex[TEX_LEN(u64, gDropDekuStickTex_WIDTH, gDropDekuStickTex_HEIGHT, 16)];
#define gDropMagicLargeTex_WIDTH 32
#define gDropMagicLargeTex_HEIGHT 32
extern u64 gDropMagicLargeTex[TEX_LEN(u64, gDropMagicLargeTex_WIDTH, gDropMagicLargeTex_HEIGHT, 16)];
#define gRupeeGreenTex_WIDTH 4
#define gRupeeGreenTex_HEIGHT 4
extern u64 gRupeeGreenTex[TEX_LEN(u64, gRupeeGreenTex_WIDTH, gRupeeGreenTex_HEIGHT, 16)];
#define gRupeeBlueTex_WIDTH 4
#define gRupeeBlueTex_HEIGHT 4
extern u64 gRupeeBlueTex[TEX_LEN(u64, gRupeeBlueTex_WIDTH, gRupeeBlueTex_HEIGHT, 16)];
#define gRupeeRedTex_WIDTH 4
#define gRupeeRedTex_HEIGHT 4
extern u64 gRupeeRedTex[TEX_LEN(u64, gRupeeRedTex_WIDTH, gRupeeRedTex_HEIGHT, 16)];
#define gRupeeOrangeTex_WIDTH 4
#define gRupeeOrangeTex_HEIGHT 4
extern u64 gRupeeOrangeTex[TEX_LEN(u64, gRupeeOrangeTex_WIDTH, gRupeeOrangeTex_HEIGHT, 16)];
#define gRupeePinkTex_WIDTH 4
#define gRupeePinkTex_HEIGHT 4
extern u64 gRupeePinkTex[TEX_LEN(u64, gRupeePinkTex_WIDTH, gRupeePinkTex_HEIGHT, 16)];
#define gRupeeSilverTex_WIDTH 4
#define gRupeeSilverTex_HEIGHT 4
extern u64 gRupeeSilverTex[TEX_LEN(u64, gRupeeSilverTex_WIDTH, gRupeeSilverTex_HEIGHT, 16)];
extern Vtx gRupeeVtx[];
extern Gfx gRupeeDL[26];
#define gGameplayKeepTex_45220_WIDTH 32
#define gGameplayKeepTex_45220_HEIGHT 32
extern u64 gGameplayKeepTex_45220[TEX_LEN(u64, gGameplayKeepTex_45220_WIDTH, gGameplayKeepTex_45220_HEIGHT, 16)];
#define gGameplayKeepTex_45A20_WIDTH 32
#define gGameplayKeepTex_45A20_HEIGHT 32
extern u64 gGameplayKeepTex_45A20[TEX_LEN(u64, gGameplayKeepTex_45A20_WIDTH, gGameplayKeepTex_45A20_HEIGHT, 16)];
#define gGameplayKeepTex_46220_WIDTH 32
#define gGameplayKeepTex_46220_HEIGHT 32
extern u64 gGameplayKeepTex_46220[TEX_LEN(u64, gGameplayKeepTex_46220_WIDTH, gGameplayKeepTex_46220_HEIGHT, 16)];
#define gRupeeLightRedTex_WIDTH 4
#define gRupeeLightRedTex_HEIGHT 4
extern u64 gRupeeLightRedTex[TEX_LEN(u64, gRupeeLightRedTex_WIDTH, gRupeeLightRedTex_HEIGHT, 16)];
#define gGameplayKeepTex_46A40_WIDTH 4
#define gGameplayKeepTex_46A40_HEIGHT 4
extern u64 gGameplayKeepTex_46A40[TEX_LEN(u64, gGameplayKeepTex_46A40_WIDTH, gGameplayKeepTex_46A40_HEIGHT, 16)];
#define gGameplayKeepTex_46A60_WIDTH 32
#define gGameplayKeepTex_46A60_HEIGHT 32
extern u64 gGameplayKeepTex_46A60[TEX_LEN(u64, gGameplayKeepTex_46A60_WIDTH, gGameplayKeepTex_46A60_HEIGHT, 16)];
#define gGameplayKeepTex_47260_WIDTH 32
#define gGameplayKeepTex_47260_HEIGHT 32
extern u64 gGameplayKeepTex_47260[TEX_LEN(u64, gGameplayKeepTex_47260_WIDTH, gGameplayKeepTex_47260_HEIGHT, 16)];
#define gUnknownStone1Tex_WIDTH 32
#define gUnknownStone1Tex_HEIGHT 32
extern u64 gUnknownStone1Tex[TEX_LEN(u64, gUnknownStone1Tex_WIDTH, gUnknownStone1Tex_HEIGHT, 16)];
#define gUnknownStone2Tex_WIDTH 32
#define gUnknownStone2Tex_HEIGHT 32
extern u64 gUnknownStone2Tex[TEX_LEN(u64, gUnknownStone2Tex_WIDTH, gUnknownStone2Tex_HEIGHT, 16)];
#define gUnusedTreeStumpTopTex_WIDTH 32
#define gUnusedTreeStumpTopTex_HEIGHT 32
extern u64 gUnusedTreeStumpTopTex[TEX_LEN(u64, gUnusedTreeStumpTopTex_WIDTH, gUnusedTreeStumpTopTex_HEIGHT, 16)];
#define gUnusedTreeStumpBarkTex_WIDTH 32
#define gUnusedTreeStumpBarkTex_HEIGHT 32
extern u64 gUnusedTreeStumpBarkTex[TEX_LEN(u64, gUnusedTreeStumpBarkTex_WIDTH, gUnusedTreeStumpBarkTex_HEIGHT, 16)];
#define gUnusedGrassBladesTex_WIDTH 64
#define gUnusedGrassBladesTex_HEIGHT 32
extern u64 gUnusedGrassBladesTex[TEX_LEN(u64, gUnusedGrassBladesTex_WIDTH, gUnusedGrassBladesTex_HEIGHT, 16)];
#define gUnusedStoneHookshotTargetTex_WIDTH 32
#define gUnusedStoneHookshotTargetTex_HEIGHT 32
extern u64 gUnusedStoneHookshotTargetTex[TEX_LEN(u64, gUnusedStoneHookshotTargetTex_WIDTH, gUnusedStoneHookshotTargetTex_HEIGHT, 16)];
#define gUnknownStone3Tex_WIDTH 32
#define gUnknownStone3Tex_HEIGHT 32
extern u64 gUnknownStone3Tex[TEX_LEN(u64, gUnknownStone3Tex_WIDTH, gUnknownStone3Tex_HEIGHT, 16)];
#define gSignRectangularSideTex_WIDTH 32
#define gSignRectangularSideTex_HEIGHT 16
extern u64 gSignRectangularSideTex[TEX_LEN(u64, gSignRectangularSideTex_WIDTH, gSignRectangularSideTex_HEIGHT, 16)];
#define gSignRectangularFrontTex_WIDTH 32
#define gSignRectangularFrontTex_HEIGHT 16
extern u64 gSignRectangularFrontTex[TEX_LEN(u64, gSignRectangularFrontTex_WIDTH, gSignRectangularFrontTex_HEIGHT, 16)];
#define gSignPostWoodTex_WIDTH 64
#define gSignPostWoodTex_HEIGHT 8
extern u64 gSignPostWoodTex[TEX_LEN(u64, gSignPostWoodTex_WIDTH, gSignPostWoodTex_HEIGHT, 16)];
#define gSignLetteringTex_WIDTH 64
#define gSignLetteringTex_HEIGHT 32
extern u64 gSignLetteringTex[TEX_LEN(u64, gSignLetteringTex_WIDTH, gSignLetteringTex_HEIGHT, 16)];
extern Vtx gRaindropVtx[];
extern Gfx gRaindropDL[4];
extern Gfx gFootShadowDL[12];
extern Vtx gFootShadowVtx[];
#define gFootShadowTex_WIDTH 32
#define gFootShadowTex_HEIGHT 64
extern u64 gFootShadowTex[TEX_LEN(u64, gFootShadowTex_WIDTH, gFootShadowTex_HEIGHT, 16)];
extern Gfx gCircleShadowDL[10];
extern Vtx gCircleShadowVtx[];
#define gCircleShadowTex_WIDTH 32
#define gCircleShadowTex_HEIGHT 32
extern u64 gCircleShadowTex[TEX_LEN(u64, gCircleShadowTex_WIDTH, gCircleShadowTex_HEIGHT, 16)];
extern Vtx gHorseShadowVtx[];
extern Gfx gHorseShadowDL[10];
#define gHorseShadowTex_WIDTH 16
#define gHorseShadowTex_HEIGHT 64
extern u64 gHorseShadowTex[TEX_LEN(u64, gHorseShadowTex_WIDTH, gHorseShadowTex_HEIGHT, 8)];
extern Vtx gDungeonDoorVtx[];
extern Gfx gDungeonDoorDL[21];
#define gDoorMetalBarsTex_WIDTH 32
#define gDoorMetalBarsTex_HEIGHT 128
extern u64 gDoorMetalBarsTex[TEX_LEN(u64, gDoorMetalBarsTex_WIDTH, gDoorMetalBarsTex_HEIGHT, 8)];
extern Vtx gDoorMetalBarsVtx[];
extern Gfx gDoorMetalBarsDL[18];
#define gGenericDungeonDoorTex_WIDTH 32
#define gGenericDungeonDoorTex_HEIGHT 64
extern u64 gGenericDungeonDoorTex[TEX_LEN(u64, gGenericDungeonDoorTex_WIDTH, gGenericDungeonDoorTex_HEIGHT, 16)];
#define gSun1Tex_WIDTH 64
#define gSun1Tex_HEIGHT 31
extern u64 gSun1Tex[TEX_LEN(u64, gSun1Tex_WIDTH, gSun1Tex_HEIGHT, 4)];
#define gSun2Tex_WIDTH 64
#define gSun2Tex_HEIGHT 16
extern u64 gSun2Tex[TEX_LEN(u64, gSun2Tex_WIDTH, gSun2Tex_HEIGHT, 4)];
#define gSun3Tex_WIDTH 64
#define gSun3Tex_HEIGHT 16
extern u64 gSun3Tex[TEX_LEN(u64, gSun3Tex_WIDTH, gSun3Tex_HEIGHT, 4)];
#define gSunEvening1Tex_WIDTH 64
#define gSunEvening1Tex_HEIGHT 31
extern u64 gSunEvening1Tex[TEX_LEN(u64, gSunEvening1Tex_WIDTH, gSunEvening1Tex_HEIGHT, 4)];
#define gSunEvening2Tex_WIDTH 64
#define gSunEvening2Tex_HEIGHT 16
extern u64 gSunEvening2Tex[TEX_LEN(u64, gSunEvening2Tex_WIDTH, gSunEvening2Tex_HEIGHT, 4)];
#define gSunEvening3Tex_WIDTH 64
#define gSunEvening3Tex_HEIGHT 16
extern u64 gSunEvening3Tex[TEX_LEN(u64, gSunEvening3Tex_WIDTH, gSunEvening3Tex_HEIGHT, 4)];
extern Gfx gKokiriDustMoteMaterialDL[9];
extern Gfx gKokiriDustMoteModelDL[3];
extern Gfx gSunDL[49];
extern Vtx gSunVtx[];
extern Vtx gKokiriDustMoteModelVtx[];
extern Gfx gLockOnReticleTriangleDL[3];
extern Vtx gLockOnReticleTriangleVtx[];
extern Vtx gEffFireVtx[];
extern Gfx gEffFire1DL[24];
extern Gfx gEffFire2DL[24];
#define gDecorativeFlameMaskTex_WIDTH 32
#define gDecorativeFlameMaskTex_HEIGHT 128
extern u64 gDecorativeFlameMaskTex[TEX_LEN(u64, gDecorativeFlameMaskTex_WIDTH, gDecorativeFlameMaskTex_HEIGHT, 4)];
#define gDecorativeFlameTex_WIDTH 32
#define gDecorativeFlameTex_HEIGHT 64
extern u64 gDecorativeFlameTex[TEX_LEN(u64, gDecorativeFlameTex_WIDTH, gDecorativeFlameTex_HEIGHT, 8)];
extern Vtx gUnusedUnknownShape1Vtx[];
extern Gfx gUnusedUnknownShape1DL[112];
extern Gfx gUnusedUnknownShape1RefDL[2];
extern Vtx gUnusedUnknownShape2Vtx[];
extern Gfx gUnusedUnknownShape2DL[100];
extern Gfx gUnusedUnknownShape2RefDL[2];
extern Vtx gUnusedUnknownShape3Vtx[];
extern Gfx gUnusedUnknownShape3DL[99];
extern Gfx gUnusedUnknownShape3RefDL[2];
#define gUnusedUpsideDownZeldaTex_WIDTH 64
#define gUnusedUpsideDownZeldaTex_HEIGHT 32
extern u64 gUnusedUpsideDownZeldaTex[TEX_LEN(u64, gUnusedUpsideDownZeldaTex_WIDTH, gUnusedUpsideDownZeldaTex_HEIGHT, 8)];
#define gDust1Tex_WIDTH 32
#define gDust1Tex_HEIGHT 32
extern u64 gDust1Tex[TEX_LEN(u64, gDust1Tex_WIDTH, gDust1Tex_HEIGHT, 8)];
#define gDust2Tex_WIDTH 32
#define gDust2Tex_HEIGHT 32
extern u64 gDust2Tex[TEX_LEN(u64, gDust2Tex_WIDTH, gDust2Tex_HEIGHT, 8)];
#define gDust3Tex_WIDTH 32
#define gDust3Tex_HEIGHT 32
extern u64 gDust3Tex[TEX_LEN(u64, gDust3Tex_WIDTH, gDust3Tex_HEIGHT, 8)];
#define gDust4Tex_WIDTH 32
#define gDust4Tex_HEIGHT 32
extern u64 gDust4Tex[TEX_LEN(u64, gDust4Tex_WIDTH, gDust4Tex_HEIGHT, 8)];
#define gDust5Tex_WIDTH 32
#define gDust5Tex_HEIGHT 32
extern u64 gDust5Tex[TEX_LEN(u64, gDust5Tex_WIDTH, gDust5Tex_HEIGHT, 8)];
#define gDust6Tex_WIDTH 32
#define gDust6Tex_HEIGHT 32
extern u64 gDust6Tex[TEX_LEN(u64, gDust6Tex_WIDTH, gDust6Tex_HEIGHT, 8)];
#define gDust7Tex_WIDTH 32
#define gDust7Tex_HEIGHT 32
extern u64 gDust7Tex[TEX_LEN(u64, gDust7Tex_WIDTH, gDust7Tex_HEIGHT, 8)];
#define gDust8Tex_WIDTH 32
#define gDust8Tex_HEIGHT 32
extern u64 gDust8Tex[TEX_LEN(u64, gDust8Tex_WIDTH, gDust8Tex_HEIGHT, 8)];
#define gCircleGlowLTex_WIDTH 32
#define gCircleGlowLTex_HEIGHT 64
extern u64 gCircleGlowLTex[TEX_LEN(u64, gCircleGlowLTex_WIDTH, gCircleGlowLTex_HEIGHT, 8)];
#define gCircleGlowRTex_WIDTH 32
#define gCircleGlowRTex_HEIGHT 64
extern u64 gCircleGlowRTex[TEX_LEN(u64, gCircleGlowRTex_WIDTH, gCircleGlowRTex_HEIGHT, 8)];
#define gCircleGlowSLTex_WIDTH 32
#define gCircleGlowSLTex_HEIGHT 64
extern u64 gCircleGlowSLTex[TEX_LEN(u64, gCircleGlowSLTex_WIDTH, gCircleGlowSLTex_HEIGHT, 8)];
#define gCircleGlowSRTex_WIDTH 32
#define gCircleGlowSRTex_HEIGHT 64
extern u64 gCircleGlowSRTex[TEX_LEN(u64, gCircleGlowSRTex_WIDTH, gCircleGlowSRTex_HEIGHT, 8)];
#define gEffBubble1Tex_WIDTH 16
#define gEffBubble1Tex_HEIGHT 16
extern u64 gEffBubble1Tex[TEX_LEN(u64, gEffBubble1Tex_WIDTH, gEffBubble1Tex_HEIGHT, 8)];
#define gEffBubble2Tex_WIDTH 16
#define gEffBubble2Tex_HEIGHT 16
extern u64 gEffBubble2Tex[TEX_LEN(u64, gEffBubble2Tex_WIDTH, gEffBubble2Tex_HEIGHT, 8)];
#define gEffSpark1Tex_WIDTH 32
#define gEffSpark1Tex_HEIGHT 32
extern u64 gEffSpark1Tex[TEX_LEN(u64, gEffSpark1Tex_WIDTH, gEffSpark1Tex_HEIGHT, 4)];
#define gEffSpark2Tex_WIDTH 32
#define gEffSpark2Tex_HEIGHT 32
extern u64 gEffSpark2Tex[TEX_LEN(u64, gEffSpark2Tex_WIDTH, gEffSpark2Tex_HEIGHT, 4)];
#define gEffSpark3Tex_WIDTH 32
#define gEffSpark3Tex_HEIGHT 32
extern u64 gEffSpark3Tex[TEX_LEN(u64, gEffSpark3Tex_WIDTH, gEffSpark3Tex_HEIGHT, 4)];
#define gEffSpark4Tex_WIDTH 32
#define gEffSpark4Tex_HEIGHT 32
extern u64 gEffSpark4Tex[TEX_LEN(u64, gEffSpark4Tex_WIDTH, gEffSpark4Tex_HEIGHT, 4)];

#if MM_BOTTLE_MODEL
extern Gfx gBottleContentsDL[];
extern Gfx gBottleGlassDL[];
#endif

#endif
